/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSpecsRouteImport } from './routes/project/specs'
import { Route as ProjectSettingsRouteImport } from './routes/project/settings'
import { Route as ProjectReleasesRouteImport } from './routes/project/releases'
import { Route as ProjectOverviewRouteImport } from './routes/project/overview'
import { Route as ProjectIssuesRouteImport } from './routes/project/issues'
import { Route as ProjectFeaturesRouteImport } from './routes/project/features'
import { Route as ProjectAgentsRouteImport } from './routes/project/agents'
import { Route as ProjectAdrsRouteImport } from './routes/project/adrs'
import { Route as ProjectActivityRouteImport } from './routes/project/activity'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSpecsRoute = ProjectSpecsRouteImport.update({
  id: '/project/specs',
  path: '/project/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSettingsRoute = ProjectSettingsRouteImport.update({
  id: '/project/settings',
  path: '/project/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectReleasesRoute = ProjectReleasesRouteImport.update({
  id: '/project/releases',
  path: '/project/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectOverviewRoute = ProjectOverviewRouteImport.update({
  id: '/project/overview',
  path: '/project/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIssuesRoute = ProjectIssuesRouteImport.update({
  id: '/project/issues',
  path: '/project/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectFeaturesRoute = ProjectFeaturesRouteImport.update({
  id: '/project/features',
  path: '/project/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectAgentsRoute = ProjectAgentsRouteImport.update({
  id: '/project/agents',
  path: '/project/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectAdrsRoute = ProjectAdrsRouteImport.update({
  id: '/project/adrs',
  path: '/project/adrs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectActivityRoute = ProjectActivityRouteImport.update({
  id: '/project/activity',
  path: '/project/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/project/activity': typeof ProjectActivityRoute
  '/project/adrs': typeof ProjectAdrsRoute
  '/project/agents': typeof ProjectAgentsRoute
  '/project/features': typeof ProjectFeaturesRoute
  '/project/issues': typeof ProjectIssuesRoute
  '/project/overview': typeof ProjectOverviewRoute
  '/project/releases': typeof ProjectReleasesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/specs': typeof ProjectSpecsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/project/activity': typeof ProjectActivityRoute
  '/project/adrs': typeof ProjectAdrsRoute
  '/project/agents': typeof ProjectAgentsRoute
  '/project/features': typeof ProjectFeaturesRoute
  '/project/issues': typeof ProjectIssuesRoute
  '/project/overview': typeof ProjectOverviewRoute
  '/project/releases': typeof ProjectReleasesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/specs': typeof ProjectSpecsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/project/activity': typeof ProjectActivityRoute
  '/project/adrs': typeof ProjectAdrsRoute
  '/project/agents': typeof ProjectAgentsRoute
  '/project/features': typeof ProjectFeaturesRoute
  '/project/issues': typeof ProjectIssuesRoute
  '/project/overview': typeof ProjectOverviewRoute
  '/project/releases': typeof ProjectReleasesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/specs': typeof ProjectSpecsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/project/activity'
    | '/project/adrs'
    | '/project/agents'
    | '/project/features'
    | '/project/issues'
    | '/project/overview'
    | '/project/releases'
    | '/project/settings'
    | '/project/specs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/project/activity'
    | '/project/adrs'
    | '/project/agents'
    | '/project/features'
    | '/project/issues'
    | '/project/overview'
    | '/project/releases'
    | '/project/settings'
    | '/project/specs'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/project/activity'
    | '/project/adrs'
    | '/project/agents'
    | '/project/features'
    | '/project/issues'
    | '/project/overview'
    | '/project/releases'
    | '/project/settings'
    | '/project/specs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectActivityRoute: typeof ProjectActivityRoute
  ProjectAdrsRoute: typeof ProjectAdrsRoute
  ProjectAgentsRoute: typeof ProjectAgentsRoute
  ProjectFeaturesRoute: typeof ProjectFeaturesRoute
  ProjectIssuesRoute: typeof ProjectIssuesRoute
  ProjectOverviewRoute: typeof ProjectOverviewRoute
  ProjectReleasesRoute: typeof ProjectReleasesRoute
  ProjectSettingsRoute: typeof ProjectSettingsRoute
  ProjectSpecsRoute: typeof ProjectSpecsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/specs': {
      id: '/project/specs'
      path: '/project/specs'
      fullPath: '/project/specs'
      preLoaderRoute: typeof ProjectSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/settings': {
      id: '/project/settings'
      path: '/project/settings'
      fullPath: '/project/settings'
      preLoaderRoute: typeof ProjectSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/releases': {
      id: '/project/releases'
      path: '/project/releases'
      fullPath: '/project/releases'
      preLoaderRoute: typeof ProjectReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/overview': {
      id: '/project/overview'
      path: '/project/overview'
      fullPath: '/project/overview'
      preLoaderRoute: typeof ProjectOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/issues': {
      id: '/project/issues'
      path: '/project/issues'
      fullPath: '/project/issues'
      preLoaderRoute: typeof ProjectIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/features': {
      id: '/project/features'
      path: '/project/features'
      fullPath: '/project/features'
      preLoaderRoute: typeof ProjectFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/agents': {
      id: '/project/agents'
      path: '/project/agents'
      fullPath: '/project/agents'
      preLoaderRoute: typeof ProjectAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/adrs': {
      id: '/project/adrs'
      path: '/project/adrs'
      fullPath: '/project/adrs'
      preLoaderRoute: typeof ProjectAdrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/activity': {
      id: '/project/activity'
      path: '/project/activity'
      fullPath: '/project/activity'
      preLoaderRoute: typeof ProjectActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectActivityRoute: ProjectActivityRoute,
  ProjectAdrsRoute: ProjectAdrsRoute,
  ProjectAgentsRoute: ProjectAgentsRoute,
  ProjectFeaturesRoute: ProjectFeaturesRoute,
  ProjectIssuesRoute: ProjectIssuesRoute,
  ProjectOverviewRoute: ProjectOverviewRoute,
  ProjectReleasesRoute: ProjectReleasesRoute,
  ProjectSettingsRoute: ProjectSettingsRoute,
  ProjectSpecsRoute: ProjectSpecsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
