use std::collections::HashMap;

use serde_json::Value as Json;

use crate::types::{HookConfig, HookTrigger, McpServerConfig, McpServerType, Permissions, Skill};
use crate::resolve::ResolvedConfig;

// ─── Provider registry ────────────────────────────────────────────────────────

/// How MCP servers are keyed in the target config file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum McpKey {
    /// `"mcpServers"` — Claude, Gemini
    McpServers,
    /// `"mcp_servers"` — Codex/OpenAI
    McpServersUnderscored,
}

impl McpKey {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::McpServers => "mcpServers",
            Self::McpServersUnderscored => "mcp_servers",
        }
    }
}

/// Where the context / system-instructions file is written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContextFile {
    /// `CLAUDE.md` — Claude Code
    ClaudeMd,
    /// `GEMINI.md` — Gemini CLI
    GeminiMd,
    /// `AGENTS.md` — Codex, Roo, Amp, Goose
    AgentsMd,
    /// Provider does not use a context file
    None,
}

impl ContextFile {
    pub fn file_name(self) -> Option<&'static str> {
        match self {
            Self::ClaudeMd => Some("CLAUDE.md"),
            Self::GeminiMd => Some("GEMINI.md"),
            Self::AgentsMd => Some("AGENTS.md"),
            Self::None => None,
        }
    }
}

/// Where native skill files are written.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillsDir {
    /// `.claude/skills/<id>/SKILL.md`
    Claude,
    /// `.gemini/skills/<id>/SKILL.md`
    Gemini,
    /// `.agents/skills/<id>/SKILL.md`
    Agents,
    None,
}

impl SkillsDir {
    pub fn base_path(self) -> Option<&'static str> {
        match self {
            Self::Claude => Some(".claude/skills"),
            Self::Gemini => Some(".gemini/skills"),
            Self::Agents => Some(".agents/skills"),
            Self::None => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct ProviderDescriptor {
    pub id: &'static str,
    pub name: &'static str,
    pub mcp_key: McpKey,
    pub context_file: ContextFile,
    pub skills_dir: SkillsDir,
    /// Whether to emit `"type"` field in MCP server entries
    pub emit_type_field: bool,
    /// HTTP/SSE URL field name ("url" or "httpUrl")
    pub http_url_field: &'static str,
}

static PROVIDERS: &[ProviderDescriptor] = &[
    ProviderDescriptor {
        id: "claude",
        name: "Claude Code",
        mcp_key: McpKey::McpServers,
        context_file: ContextFile::ClaudeMd,
        skills_dir: SkillsDir::Claude,
        emit_type_field: false,
        http_url_field: "url",
    },
    ProviderDescriptor {
        id: "gemini",
        name: "Gemini CLI",
        mcp_key: McpKey::McpServers,
        context_file: ContextFile::GeminiMd,
        skills_dir: SkillsDir::Gemini,
        emit_type_field: true,
        http_url_field: "httpUrl",
    },
    ProviderDescriptor {
        id: "codex",
        name: "OpenAI Codex",
        mcp_key: McpKey::McpServersUnderscored,
        context_file: ContextFile::AgentsMd,
        skills_dir: SkillsDir::Agents,
        emit_type_field: true,
        http_url_field: "url",
    },
];

pub fn get_provider(id: &str) -> Option<&'static ProviderDescriptor> {
    PROVIDERS.iter().find(|p| p.id == id)
}

pub fn list_providers() -> &'static [ProviderDescriptor] {
    PROVIDERS
}

// ─── Output ───────────────────────────────────────────────────────────────────

/// The content generated by the compiler for a given provider.
/// All values are strings ready to write; no filesystem access required.
#[derive(Debug, Clone, Default)]
pub struct CompileOutput {
    /// MCP server entries to inject into the target config file.
    /// Key = provider's `mcp_key` value, value = JSON object mapping server ID → entry.
    pub mcp_servers: Json,

    /// Context file content (CLAUDE.md / GEMINI.md / AGENTS.md).
    /// `None` if the provider has no context file or there is no content to emit.
    pub context_content: Option<String>,

    /// Skill files: path relative to project root → file content.
    /// e.g. `".claude/skills/my-skill/SKILL.md" → "---\nname: my-skill\n..."`.
    pub skill_files: HashMap<String, String>,

    /// Claude settings patches: `allow` and `deny` tool lists, hooks.
    /// Only populated for the `claude` provider.
    pub claude_settings_patch: Option<Json>,
}

// ─── Main entry point ─────────────────────────────────────────────────────────

/// Compile a resolved agent config into provider-ready content.
/// Returns `None` if the provider ID is not recognised.
pub fn compile(resolved: &ResolvedConfig, provider_id: &str) -> Option<CompileOutput> {
    let desc = get_provider(provider_id)?;
    let mut out = CompileOutput::default();

    out.mcp_servers = build_mcp_servers(desc, &resolved.mcp_servers);
    out.context_content = build_context_content(desc, resolved);
    out.skill_files = build_skill_files(desc, &resolved.skills);

    if provider_id == "claude" {
        out.claude_settings_patch =
            build_claude_settings_patch(&resolved.permissions, &[]);
    }

    Some(out)
}

// ─── MCP server serialisation ─────────────────────────────────────────────────

fn build_mcp_servers(desc: &ProviderDescriptor, servers: &[McpServerConfig]) -> Json {
    let mut map = serde_json::Map::new();

    // Ship's own self-hosted MCP server is always injected first.
    map.insert(
        "ship".to_string(),
        ship_server_entry(desc.emit_type_field),
    );

    for s in servers {
        if s.disabled {
            continue;
        }
        map.insert(s.id.clone(), server_entry(desc, s));
    }

    Json::Object(map)
}

fn server_entry(desc: &ProviderDescriptor, s: &McpServerConfig) -> Json {
    let mut entry = serde_json::json!({});
    match s.server_type {
        McpServerType::Stdio => {
            entry["command"] = Json::String(s.command.clone());
            if !s.args.is_empty() {
                entry["args"] = serde_json::json!(s.args);
            }
            if !s.env.is_empty() {
                entry["env"] = serde_json::json!(s.env);
            }
            if desc.emit_type_field {
                entry["type"] = Json::String("stdio".to_string());
            }
        }
        McpServerType::Sse | McpServerType::Http => {
            if let Some(url) = &s.url {
                entry[desc.http_url_field] = Json::String(url.clone());
            }
            if desc.emit_type_field {
                let t = if s.server_type == McpServerType::Sse {
                    "sse"
                } else {
                    "http"
                };
                entry["type"] = Json::String(t.to_string());
            }
        }
    }
    if let Some(t) = s.timeout_secs {
        entry["startup_timeout_sec"] = serde_json::json!(t);
    }
    entry
}

fn ship_server_entry(emit_type: bool) -> Json {
    let mut e = serde_json::json!({
        "command": "ship",
        "args": ["mcp", "serve"]
    });
    if emit_type {
        e["type"] = Json::String("stdio".to_string());
    }
    e
}

// ─── Context file content ─────────────────────────────────────────────────────

fn build_context_content(desc: &ProviderDescriptor, resolved: &ResolvedConfig) -> Option<String> {
    if desc.context_file == ContextFile::None {
        return None;
    }

    let mut parts: Vec<String> = Vec::new();

    // Rules
    for rule in &resolved.rules {
        parts.push(rule.content.trim().to_string());
    }

    // Mode notice
    if let Some(mode) = &resolved.active_mode {
        parts.push(format!("<!-- ship: active mode = {} -->", mode));
    }

    if parts.is_empty() {
        return None;
    }

    Some(parts.join("\n\n"))
}

// ─── Skill files ──────────────────────────────────────────────────────────────

fn build_skill_files(desc: &ProviderDescriptor, skills: &[Skill]) -> HashMap<String, String> {
    let Some(base) = desc.skills_dir.base_path() else {
        return HashMap::new();
    };
    skills
        .iter()
        .map(|skill| {
            let path = format!("{}/{}/SKILL.md", base, skill.id);
            let content = format_skill_file(skill);
            (path, content)
        })
        .collect()
}

fn format_skill_file(skill: &Skill) -> String {
    let description = skill
        .description
        .as_deref()
        .unwrap_or("No description provided.");
    format!(
        "---\nname: {}\ndescription: {}\n---\n\n{}",
        skill.id, description, skill.content
    )
}

// ─── Claude settings patch ────────────────────────────────────────────────────

pub fn build_claude_settings_patch(
    permissions: &Permissions,
    hooks: &[HookConfig],
) -> Option<Json> {
    let has_perms = has_permission_overrides(permissions);
    let has_hooks = !hooks.is_empty();
    if !has_perms && !has_hooks {
        return None;
    }

    let mut patch = serde_json::json!({});

    if has_perms {
        patch["permissions"] = serde_json::json!({
            "allow": permissions.tools.allow,
            "deny": permissions.tools.deny,
        });
    }

    if has_hooks {
        let mut by_trigger: HashMap<&str, Vec<Json>> = HashMap::new();
        for hook in hooks {
            let key = match hook.trigger {
                HookTrigger::PreToolUse => "PreToolUse",
                HookTrigger::PostToolUse => "PostToolUse",
                HookTrigger::Notification => "Notification",
                HookTrigger::Stop => "Stop",
                HookTrigger::SubagentStop => "SubagentStop",
                HookTrigger::PreCompact => "PreCompact",
            };
            let mut entry = serde_json::json!({ "type": "command", "command": hook.command });
            if let Some(m) = &hook.matcher {
                entry["matcher"] = Json::String(m.clone());
            }
            by_trigger.entry(key).or_default().push(entry);
        }
        patch["hooks"] = serde_json::json!(by_trigger);
    }

    Some(patch)
}

fn has_permission_overrides(p: &Permissions) -> bool {
    let default_allow = p.tools.allow.is_empty()
        || (p.tools.allow.len() == 1 && p.tools.allow[0] == "*");
    !default_allow || !p.tools.deny.is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::resolve::ResolvedConfig;
    use crate::types::{McpServerConfig, McpServerType, Permissions, Skill};

    fn make_server(id: &str) -> McpServerConfig {
        McpServerConfig {
            id: id.to_string(),
            name: id.to_string(),
            command: "npx".to_string(),
            args: vec!["-y".to_string(), format!("@mcp/{}", id)],
            env: Default::default(),
            scope: "project".to_string(),
            server_type: McpServerType::Stdio,
            url: None,
            disabled: false,
            timeout_secs: None,
        }
    }

    fn minimal_resolved(servers: Vec<McpServerConfig>) -> ResolvedConfig {
        ResolvedConfig {
            providers: vec!["claude".to_string()],
            model: None,
            max_cost_per_session: None,
            max_turns: None,
            mcp_servers: servers,
            skills: vec![],
            rules: vec![],
            permissions: Permissions::default(),
            active_mode: None,
        }
    }

    #[test]
    fn ship_server_always_present() {
        let resolved = minimal_resolved(vec![]);
        let out = compile(&resolved, "claude").unwrap();
        let servers = out.mcp_servers.as_object().unwrap();
        assert!(servers.contains_key("ship"));
    }

    #[test]
    fn disabled_servers_excluded() {
        let mut s = make_server("github");
        s.disabled = true;
        let resolved = minimal_resolved(vec![s]);
        let out = compile(&resolved, "claude").unwrap();
        let servers = out.mcp_servers.as_object().unwrap();
        assert!(!servers.contains_key("github"));
    }

    #[test]
    fn active_servers_included() {
        let resolved = minimal_resolved(vec![make_server("linear")]);
        let out = compile(&resolved, "claude").unwrap();
        let servers = out.mcp_servers.as_object().unwrap();
        assert!(servers.contains_key("linear"));
    }

    #[test]
    fn unknown_provider_returns_none() {
        let resolved = minimal_resolved(vec![]);
        assert!(compile(&resolved, "unknown-ai").is_none());
    }

    #[test]
    fn skill_files_use_provider_dir() {
        let resolved = ResolvedConfig {
            skills: vec![Skill {
                id: "my-skill".to_string(),
                name: "My Skill".to_string(),
                description: Some("Does stuff.".to_string()),
                version: None,
                author: None,
                content: "Do the thing: $ARGUMENTS".to_string(),
                source: Default::default(),
            }],
            ..minimal_resolved(vec![])
        };
        let out = compile(&resolved, "claude").unwrap();
        assert!(out.skill_files.contains_key(".claude/skills/my-skill/SKILL.md"));

        let gemini = compile(&resolved, "gemini").unwrap();
        assert!(gemini.skill_files.contains_key(".gemini/skills/my-skill/SKILL.md"));
    }
}
