pub mod agents;
pub mod provider;

mod claude;
mod codex;
mod context;
mod cursor;
mod gemini;
mod mcp;
mod opencode;
mod plugins;
mod skills;

#[cfg(test)]
mod tests;

use std::collections::HashMap;

use serde_json::Value as Json;

use crate::resolve::ResolvedConfig;
use crate::types::PluginsManifest;

// ─── Re-exports for lib.rs public surface ─────────────────────────────────────

pub use claude::build_claude_settings_patch;
pub use cursor::{CURSOR_PERMISSIVE_ALLOW, translate_to_cursor_permission};
pub use provider::{
    AgentsDir, ContextFile, McpKey, ProviderDescriptor, ProviderFeatureFlags, SkillsDir,
    get_provider, list_providers,
};

// ─── Output ───────────────────────────────────────────────────────────────────

/// The content generated by the compiler for a given provider.
/// All values are strings ready to write; no filesystem access required.
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct CompileOutput {
    /// MCP server entries to inject into the target config file.
    /// Key = provider's `mcp_key` value, value = JSON object mapping server ID → entry.
    pub mcp_servers: Json,

    /// Project-relative path where the MCP config file should be written,
    /// e.g. `".mcp.json"` for Claude or `".cursor/mcp.json"` for Cursor.
    /// `None` when the provider merges MCP into a larger settings file.
    pub mcp_config_path: Option<String>,

    /// Context file content (CLAUDE.md / GEMINI.md / AGENTS.md).
    /// `None` if the provider has no context file or there is no content to emit.
    pub context_content: Option<String>,

    /// Skill files: path relative to project root → file content.
    /// e.g. `".claude/skills/my-skill/SKILL.md" → "---\nname: my-skill\n..."`.
    pub skill_files: HashMap<String, String>,

    /// Claude settings patch: `permissions`, `hooks`, agent limits.
    /// Only populated for the `claude` provider.
    pub claude_settings_patch: Option<Json>,

    /// Codex config patch: `[mcp_servers.<id>]` TOML tables.
    /// Only populated for the `codex` provider.
    /// Merge into `.codex/config.toml`.
    pub codex_config_patch: Option<String>,

    /// Gemini settings patch: `hooks` section for `.gemini/settings.json`.
    /// Only populated for the `gemini` provider when hooks are present.
    /// Merge alongside `mcpServers` in `.gemini/settings.json`.
    pub gemini_settings_patch: Option<Json>,

    /// Gemini policy file content for `.gemini/policies/ship.toml`.
    /// Only populated for the `gemini` provider when permissions are non-default.
    /// Decisions: `allow`, `deny`, `ask_user`. Tool names: `shell`, `mcp`,
    /// `file_read`, `file_write`, `web_fetch`.
    pub gemini_policy_patch: Option<String>,

    /// Cursor hooks file: full `.cursor/hooks.json` content.
    /// Only populated for the `cursor` provider when hooks are present.
    pub cursor_hooks_patch: Option<Json>,

    /// Cursor permissions: `{ "version": 1, "permissions": { "allow": [...], "deny": [...] } }`
    /// Written to `.cursor/cli.json` (project) or `~/.cursor/cli-config.json` (global).
    /// Applies to both Cursor IDE agents and the Cursor CLI.
    /// Only populated when permissions are non-default. Never emits a permissive allow-all
    /// unless the user explicitly supplies the typed wildcard patterns.
    pub cursor_cli_permissions: Option<Json>,

    /// Per-file rule output for providers that use individual rule files.
    /// Key = relative path (e.g. `.cursor/rules/style.mdc`), value = file content.
    /// Populated for Cursor (per-file .mdc). Other providers use `context_content`.
    pub rule_files: HashMap<String, String>,

    /// Plugin install intent declared by the active preset.
    /// This is a pure output artifact — the compiler never installs plugins.
    /// The CLI/runtime reads this after compilation and executes the lifecycle.
    pub plugins_manifest: PluginsManifest,

    /// Provider-native agent definition files.
    /// Key = path relative to project root (e.g. `.claude/agents/monitor.md`).
    /// Value = file content. Written verbatim by the CLI.
    pub agent_files: HashMap<String, String>,

    /// Cursor-only: `.cursor/environment.json` content.
    /// Only populated when `cursor_environment` is set in the resolved config.
    pub cursor_environment_json: Option<Json>,

    /// OpenCode-only: full `opencode.json` content (model + MCP + extras).
    /// Only populated for the `opencode` provider.
    pub opencode_config_patch: Option<Json>,

    /// Codex-only: `.codex/hooks.json` content.
    /// Only populated for the `codex` provider.
    pub codex_hooks_json: Option<Json>,

    /// Resolved actor event subscription namespaces for this agent.
    ///
    /// Combines:
    /// - `ship.{suffix}` entries inferred from skill artifact declarations.
    /// - `{skill.id}.` custom namespace for each skill.
    ///
    /// The runtime reads this at actor spawn time to replace the hardcoded
    /// `subscribe_namespaces` list in `ActorConfig`.
    pub event_subscriptions: Vec<String>,
}

// ─── Main entry point ─────────────────────────────────────────────────────────

/// Compile a resolved agent config into provider-ready content.
/// Returns `None` if the provider ID is not recognised.
pub fn compile(resolved: &ResolvedConfig, provider_id: &str) -> Option<CompileOutput> {
    let desc = get_provider(provider_id)?;
    let flags = desc.feature_flags();
    let mut out = CompileOutput::default();

    // Only emit MCP config for providers that support it.
    if flags.supports_mcp {
        let studio_url = resolved.studio_mcp_url.as_deref();
        // Use provider-specific MCP builders when available (for per-server fields).
        out.mcp_servers = match provider_id {
            "gemini" => gemini::build_gemini_mcp_servers(desc, &resolved.mcp_servers, studio_url),
            "cursor" => cursor::build_cursor_mcp_servers(desc, &resolved.mcp_servers, studio_url),
            _ => mcp::build_mcp_servers(desc, &resolved.mcp_servers, studio_url),
        };
        out.mcp_config_path = desc.mcp_config_path.map(String::from);
    } else {
        out.mcp_servers = serde_json::json!({});
    }
    out.context_content = context::build_context_content(desc, resolved);
    out.skill_files = skills::build_skill_files(desc, &resolved.skills);
    out.event_subscriptions = skills::resolve_event_subscriptions(&resolved.skills);

    // Compile agent profiles for this provider
    let profile_agents = agents::compile_agent_profiles(&resolved.agent_profiles, provider_id);
    out.agent_files.extend(profile_agents);

    if provider_id == "claude" {
        out.claude_settings_patch = claude::build_claude_settings_patch(
            &resolved.permissions,
            &resolved.hooks,
            resolved.model.as_deref(),
            resolved.claude_settings_extra.as_ref(),
            &resolved.env,
            &resolved.available_models,
            resolved.claude_theme.as_deref(),
            resolved.claude_auto_updates,
            resolved.claude_include_co_authored_by,
        );
        // Legacy team agents (passthrough from .ship/agents/teams/claude/)
        if let Some(base) = desc.agents_dir.base_path() {
            for (filename, content) in &resolved.claude_team_agents {
                out.agent_files
                    .insert(format!("{base}/{filename}"), content.clone());
            }
        }
    }

    if provider_id == "codex" {
        out.codex_config_patch = codex::build_codex_config_patch(resolved);
        out.codex_hooks_json = Some(codex::build_codex_hooks_json());
    }

    if provider_id == "gemini" {
        out.gemini_settings_patch = gemini::build_gemini_settings_patch(resolved);
        out.gemini_policy_patch = gemini::build_gemini_policy_patch(&resolved.permissions);
    }

    if provider_id == "cursor" {
        out.rule_files = cursor::build_cursor_rule_files(&resolved.rules);
        out.cursor_hooks_patch = cursor::build_cursor_hooks_patch(&resolved.hooks);
        // cursor_cli_permissions is now merged with cursor_settings_extra via build_cursor_cli_json
        out.cursor_cli_permissions = cursor::build_cursor_cli_json(resolved);
        out.cursor_environment_json = cursor::build_cursor_environment(resolved);
    }

    if provider_id == "opencode" {
        out.opencode_config_patch = opencode::build_opencode_config_patch(resolved);
    }

    out.plugins_manifest = plugins::build_plugins_manifest(&resolved.plugins, provider_id);

    Some(out)
}
