// @ts-nocheck
// This file is auto-generated by tauri-specta. Do not edit manually.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<ProjectDiscovery[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveProject() : Promise<Result<ProjectInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveProject(path: string) : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens a folder picker. If the chosen directory has no .ship, initialises one.
 * Sets the result as the active project.
 */
async pickAndOpenProject() : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_and_open_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new project by picking a folder and initializing .ship
 */
async createNewProject() : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens a folder picker and returns the selected directory path.
 */
async pickProjectDirectory() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_project_directory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates (or initializes) a project from explicit onboarding options.
 */
async createProjectWithOptions(directory: string, name: string | null, description: string | null, config: ProjectConfig | null) : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project_with_options", { directory, name, description, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameProjectCmd(path: string, name: string) : Promise<Result<ProjectInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_project_cmd", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Auto-detect current project from the working directory (for local e2e).
 */
async detectCurrentProject() : Promise<Result<ProjectInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_current_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAdrsCmd() : Promise<Result<AdrEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_adrs_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNewAdr(title: string, context: string, decision: string) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_adr", { title, context, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAdrCmd(id: string) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_adr_cmd", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAdrCmd(id: string, adr: ADR) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_adr_cmd", { id, adr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveAdrCmd(id: string, newStatus: string) : Promise<Result<AdrEntry, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_adr_cmd", { id, newStatus }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAdrCmd(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_adr_cmd", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listReleasesCmd() : Promise<Result<ReleaseInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_releases_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReleaseCmd(fileName: string) : Promise<Result<ReleaseDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_release_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createReleaseCmd(version: string, content: string, status: string | null, targetDate: string | null, supported: boolean | null, tags: string[] | null) : Promise<Result<ReleaseDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_release_cmd", { version, content, status, targetDate, supported, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateReleaseCmd(fileName: string, content: string, version: string | null, status: string | null, targetDate: string | null, supported: boolean | null, tags: string[] | null) : Promise<Result<ReleaseDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_release_cmd", { fileName, content, version, status, targetDate, supported, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFeaturesCmd() : Promise<Result<FeatureInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_features_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFeatureCmd(fileName: string) : Promise<Result<FeatureDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_feature_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFeatureCmd(title: string, content: string, release: string | null, branch: string | null) : Promise<Result<FeatureDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_feature_cmd", { title, content, release, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFeatureCmd(fileName: string, content: string) : Promise<Result<FeatureDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_feature_cmd", { fileName, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async featureStartCmd(fileName: string) : Promise<Result<FeatureDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("feature_start_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async featureDoneCmd(fileName: string) : Promise<Result<FeatureDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("feature_done_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFeatureDocumentationCmd(fileName: string, content: string, status: string | null, verifyNow: boolean | null) : Promise<Result<FeatureDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_feature_documentation_cmd", { fileName, content, status, verifyNow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTemplateCmd(kind: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_template_cmd", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVisionCmd() : Promise<Result<VisionDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_vision_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVisionCmd(content: string) : Promise<Result<VisionDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_vision_cmd", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNotesCmd(scope: string | null) : Promise<Result<NoteInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes_cmd", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNoteCmd(id: string, scope: string | null) : Promise<Result<NoteDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note_cmd", { id, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNoteCmd(title: string, content: string, scope: string | null) : Promise<Result<NoteDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note_cmd", { title, content, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNoteCmd(id: string, content: string, scope: string | null) : Promise<Result<NoteDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note_cmd", { id, content, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNoteCmd(id: string, scope: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note_cmd", { id, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRulesCmd() : Promise<Result<Rule[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_rules_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRuleCmd(fileName: string) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_rule_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRuleCmd(fileName: string, content: string) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_rule_cmd", { fileName, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRuleCmd(fileName: string, content: string) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_rule_cmd", { fileName, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRuleCmd(fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule_cmd", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPermissionsCmd() : Promise<Result<Permissions, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_permissions_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePermissionsCmd(permissions: Permissions) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_permissions_cmd", { permissions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPermissionToolVocabularyCmd() : Promise<Result<ProviderToolVocabularyEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_permission_tool_vocabulary_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaceEditorsCmd() : Promise<Result<WorkspaceEditorInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspace_editors_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGitBranchesCmd() : Promise<Result<GitBranchInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_git_branches_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceCmd(branch: string) : Promise<Result<Workspace | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspacesCmd() : Promise<Result<Workspace[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncWorkspaceCmd(branch: string | null) : Promise<Result<Workspace, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_workspace_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspaceCmd(branch: string, workspaceType: string | null, environmentId: string | null, agent: WorkspaceAgentOverridesInput | null, featureId: string | null, releaseId: string | null, isWorktree: boolean | null, worktreePath: string | null) : Promise<Result<Workspace, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace_cmd", { branch, workspaceType, environmentId, agent, featureId, releaseId, isWorktree, worktreePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateWorkspaceCmd(branch: string) : Promise<Result<Workspace, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_workspace_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkspaceModeCmd(branch: string, modeId: string | null) : Promise<Result<Workspace, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace_mode_cmd", { branch, modeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorkspaceCmd(branch: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workspace_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveWorkspaceSessionCmd(branch: string) : Promise<Result<WorkspaceSession | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_workspace_session_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaceSessionsCmd(branch: string | null, limit: number | null) : Promise<Result<WorkspaceSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspace_sessions_cmd", { branch, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceProviderMatrixCmd(branch: string, modeId: string | null) : Promise<Result<WorkspaceProviderMatrix, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_provider_matrix_cmd", { branch, modeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async repairWorkspaceCmd(branch: string, dryRun: boolean | null) : Promise<Result<WorkspaceRepairReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("repair_workspace_cmd", { branch, dryRun }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startWorkspaceSessionCmd(branch: string, goal: string | null, modeId: string | null, provider: string | null) : Promise<Result<WorkspaceSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_workspace_session_cmd", { branch, goal, modeId, provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endWorkspaceSessionCmd(branch: string, summary: string | null, updatedFeatureIds: string[] | null) : Promise<Result<WorkspaceSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_workspace_session_cmd", { branch, summary, updatedFeatureIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaceChangesCmd(branch: string) : Promise<Result<WorkspaceFileChange[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspace_changes_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspaceGitStatusCmd(branch: string) : Promise<Result<WorkspaceGitStatusSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_git_status_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGitStatusForPathCmd(path: string) : Promise<Result<WorkspaceGitStatusSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_status_for_path_cmd", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBranchDetailCmd(branch: string) : Promise<Result<BranchDetailSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_detail_cmd", { branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBranchFileDiffCmd(branch: string, path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_file_diff_cmd", { branch, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openWorkspaceEditorCmd(branch: string, editor: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_workspace_editor_cmd", { branch, editor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startWorkspaceTerminalCmd(branch: string, provider: string | null, cols: number | null, rows: number | null) : Promise<Result<WorkspaceTerminalSessionInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_workspace_terminal_cmd", { branch, provider, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readWorkspaceTerminalCmd(sessionId: string, maxBytes: number | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_workspace_terminal_cmd", { sessionId, maxBytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeWorkspaceTerminalCmd(sessionId: string, input: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_workspace_terminal_cmd", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizeWorkspaceTerminalCmd(sessionId: string, cols: number, rows: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_workspace_terminal_cmd", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopWorkspaceTerminalCmd(sessionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_workspace_terminal_cmd", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transitionWorkspaceCmd(branch: string, status: string) : Promise<Result<Workspace, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transition_workspace_cmd", { branch, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentBranchCmd() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_branch_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEventsCmd(since: number | null, limit: number | null) : Promise<Result<EventRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_events_cmd", { since, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ingestEventsCmd() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ingest_events_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLog() : Promise<Result<LogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRuntimePerfCmd() : Promise<Result<RuntimePerfSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_runtime_perf_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<ProjectConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectConfig() : Promise<Result<ProjectConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProjectConfig(config: ProjectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAppSettings(config: ProjectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_app_settings", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModesCmd() : Promise<Result<ModeConfig[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_modes_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addModeCmd(mode: ModeConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_mode_cmd", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeModeCmd(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_mode_cmd", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModeCmd(id: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_mode_cmd", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveModeCmd() : Promise<Result<ModeConfig | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_mode_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpServersCmd() : Promise<Result<McpServerConfig[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_servers_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMcpServerCmd(server: McpServerConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_mcp_server_cmd", { server }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeMcpServerCmd(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_mcp_server_cmd", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateMcpServersCmd(servers: McpServerConfig[]) : Promise<Result<McpValidationReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_mcp_servers_cmd", { servers }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeMcpServersCmd(servers: McpServerConfig[], scope: string | null) : Promise<Result<McpProbeReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_mcp_servers_cmd", { servers, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentDiscoveryCacheCmd(scope: string | null) : Promise<Result<AgentDiscoveryCache, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_discovery_cache_cmd", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshAgentDiscoveryCacheCmd(scope: string | null) : Promise<Result<AgentDiscoveryCache, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_agent_discovery_cache_cmd", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchMcpRegistryCmd(query: string | null, limit: number | null) : Promise<Result<McpRegistryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_mcp_registry_cmd", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillsCmd(scope: string | null) : Promise<Result<Skill[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills_cmd", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillToolHintsCmd(scope: string | null) : Promise<Result<SkillToolHint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_tool_hints_cmd", { scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSkillCmd(id: string, scope: string | null) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_skill_cmd", { id, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSkillCmd(id: string, name: string, content: string, scope: string | null) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_skill_cmd", { id, name, content, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSkillCmd(id: string, name: string | null, content: string | null, scope: string | null) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_skill_cmd", { id, name, content, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSkillCmd(id: string, scope: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill_cmd", { id, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installSkillFromSourceCmd(source: string, skillId: string, gitRef: string | null, repoPath: string | null, scope: string | null, force: boolean | null) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_skill_from_source_cmd", { source, skillId, gitRef, repoPath, scope, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all supported agent providers with enabled + installed status and known models.
 */
async listProvidersCmd() : Promise<Result<ProviderInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_providers_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the known models for a specific provider (static list).
 */
async listModelsCmd(providerId: string) : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models_cmd", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the resolved AgentConfig for the current branch/project state.
 * Pass the feature's agent config JSON string if on a feature branch; `null` otherwise.
 */
async getAgentConfigCmd() : Promise<Result<AgentConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_config_cmd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return all embedded catalog entries (MCP servers).
 */
async listCatalogCmd() : Promise<CatalogEntry[]> {
    return await TAURI_INVOKE("list_catalog_cmd");
},
/**
 * Return catalog entries filtered by kind.
 */
async listCatalogByKindCmd(kind: CatalogKind) : Promise<CatalogEntry[]> {
    return await TAURI_INVOKE("list_catalog_by_kind_cmd", { kind });
},
/**
 * Search the catalog by name, description, or tag.
 */
async searchCatalogCmd(query: string) : Promise<CatalogEntry[]> {
    return await TAURI_INVOKE("search_catalog_cmd", { query });
},
async exportAgentConfigCmd(target: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_agent_config_cmd", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAgentConfigCmd(target: string, includePermissions: boolean | null) : Promise<Result<ProviderImportReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_agent_config_cmd", { target, includePermissions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateAdrCmd(title: string, context: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_adr_cmd", { title, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transformTextCmd(instruction: string, text: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transform_text_cmd", { instruction, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
shipEvent: ShipEvent
}>({
shipEvent: "ship-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The full ADR document returned to the UI / MCP.
 */
export type ADR = { metadata: AdrMetadata; 
/**
 * Background, constraints, requirements — freeform text.
 */
context: string; 
/**
 * The committed decision register — markdown narrative.
 */
decision: string }
/**
 * List entry / summary — used by list commands and MCP resources.
 */
export type AdrEntry = { id: string; file_name: string; path: string; status: AdrStatus; adr: ADR }
export type AdrMetadata = { id: string; title: string; date: string; tags?: string[]; supersedes_id?: string | null }
export type AdrStatus = "proposed" | "accepted" | "rejected" | "superseded" | "deprecated"
/**
 * Fully resolved, in-memory agent configuration for the current branch/feature.
 * 
 * Not stored as a file. Computed by [`resolve_agent_config`] from:
 * 1. Project defaults (`ship.toml` + `agents/` directory)
 * 2. Active mode overrides
 * 3. Feature `[agent]` block (thin overrides)
 * 
 * A snapshot of key IDs is stored in the Workspace SQLite record for the UI.
 */
export type AgentConfig = { 
/**
 * Active provider IDs (e.g. `["claude"]`). Inherited from project or overridden by feature.
 */
providers: string[]; 
/**
 * Model override — `None` means use the provider's default.
 */
model: string | null; 
/**
 * Resolved MCP servers (project list, filtered by mode + feature).
 */
mcp_servers: McpServerConfig[]; 
/**
 * Resolved skills (project + user effective list, filtered by feature).
 */
skills: Skill[]; 
/**
 * Rules from `agents/rules/` — always active, no filtering.
 */
rules: Rule[]; 
/**
 * Resolved permissions from `agents/permissions.toml`.
 */
permissions: Permissions; 
/**
 * Active mode ID if one is set in `ship.toml`.
 */
active_mode: string | null }
export type AgentDiscoveryCache = { version: number; 
/**
 * Unix epoch seconds as string.
 */
updated_at: string; mcp_tools: Partial<{ [key in string]: McpDiscoveredTool[] }>; shell_commands: string[]; filesystem_paths: string[] }
export type AgentLayerConfig = { 
/**
 * Skill IDs to load for all sessions in this project.
 */
skills?: string[]; 
/**
 * Legacy alias for global instruction skill IDs.
 * Prompts are modeled as skills in Ship.
 */
prompts?: string[]; 
/**
 * Context files/folders to preload for agents.
 */
context?: string[] }
export type AgentLimits = { require_confirmation?: string[] }
/**
 * Configuration for the AI pass-through CLI.
 * Ship does not call any AI APIs directly — it spawns the configured CLI binary.
 * Supported providers: "claude" (Claude Code CLI), "gemini", "codex".
 * "chatgpt" is still accepted as a backwards-compatible alias.
 */
export type AiConfig = { 
/**
 * Which AI CLI to use. Defaults to "claude".
 */
provider: string | null; 
/**
 * Optional model identifier for UI/agent selection context.
 */
model: string | null; 
/**
 * Override the binary path if it's not on PATH. Defaults to the provider name.
 */
cli_path: string | null }
export type BranchDetailSummary = { branch: string; base_branch: string; ahead: number; behind: number; touched_files: number; insertions: number; deletions: number; has_workspace: boolean; changes: BranchFileChange[] }
export type BranchFileChange = { status: string; path: string; insertions: number; deletions: number }
/**
 * A browsable catalog entry for MCP servers.
 * 
 * For alpha this is an embedded static list. In the future it can be supplemented
 * or replaced by an API call (MCP registry and/or Ship-hosted catalog).
 */
export type CatalogEntry = { 
/**
 * Stable identifier (slug).
 */
id: string; name: string; description: string; kind: CatalogKind; tags: string[]; 
/**
 * Author or organisation name.
 */
author: string | null; 
/**
 * Canonical URL for the skill/server (docs or registry page).
 */
source_url: string | null; 
/**
 * Shell command to install the server (e.g. `npx -y @mcp/server-filesystem`).
 */
install_command: string | null; 
/**
 * For MCP servers: the runtime command (e.g. `npx`).
 */
command: string | null; 
/**
 * For MCP servers: default args (placeholders like `{path}` are replaced at install time).
 */
args: string[] }
export type CatalogKind = "skill" | "mcp-server"
export type CommandPermissions = { allow?: string[]; deny?: string[] }
export type EventAction = "init" | "create" | "update" | "delete" | "move" | "note" | "link" | "add" | "remove" | "set" | "clear" | "scan" | "promote" | "start" | "stop" | "log"
export type EventEntity = "project" | "workspace" | "session" | "note" | "spec" | "adr" | "feature" | "release" | "config" | "mode" | "prompt" | "plugin" | "ghost" | "time" | "agent" | "mcp"
export type EventRecord = { seq: number; timestamp: string; actor: string; entity: EventEntity; action: EventAction; subject: string; details?: string | null }
export type FeatureCriterionItem = { id: string; text: string; met: boolean }
export type FeatureDeclaration = { narrative: string; acceptance_criteria?: FeatureDeclarationCriterion[] }
export type FeatureDeclarationCriterion = { text: string; has_pass_fail_condition: boolean }
export type FeatureDelta = { declaration_missing: boolean; status_missing: boolean; unmet_acceptance_criteria?: string[]; failing_checks?: string[]; missing_pass_fail_criteria?: string[]; drift_score: number; actionable_items?: string[] }
export type FeatureDocument = { id: string; file_name: string; title: string; status: string; release_id?: string | null; active_target_id?: string | null; branch?: string | null; description?: string | null; path: string; updated: string; content: string; docs_status?: string | null; docs_revision?: number | null; docs_updated_at?: string | null; docs_content?: string | null; todos?: FeatureTodoItem[]; acceptance_criteria?: FeatureCriterionItem[]; model?: FeatureModel | null }
export type FeatureInfo = { id: string; file_name: string; title: string; status: string; release_id?: string | null; active_target_id?: string | null; branch?: string | null; description?: string | null; docs_status?: string | null; path: string; updated: string }
export type FeatureModel = { declaration: FeatureDeclaration; status: FeatureObservedStatus; delta: FeatureDelta }
export type FeatureObservedStatus = { narrative: string; checks?: FeatureStatusCheck[] }
export type FeatureStatusCheck = { text: string; passing: boolean }
export type FeatureTodoItem = { id: string; text: string; completed: boolean }
export type FsPermissions = { allow?: string[]; deny?: string[] }
export type GitBranchInfo = { name: string; current: boolean; base_branch: string; ahead: number; behind: number; touched_files: number; insertions: number; deletions: number }
/**
 * Controls which parts of .ship/ are committed to git.
 */
export type GitConfig = { 
/**
 * Paths/globs that should be gitignored (relative to .ship/).
 */
ignore?: string[]; 
/**
 * Paths/globs that should be committed (relative to .ship/).
 */
commit?: string[] }
/**
 * A shell command executed on a lifecycle event.
 */
export type HookConfig = { id: string; trigger: HookTrigger; 
/**
 * Glob/regex pattern to match tool name (e.g. "Bash", "mcp__*"). Empty = all tools.
 */
matcher?: string | null; 
/**
 * Optional timeout for the hook command in milliseconds.
 */
timeout_ms?: number | null; 
/**
 * Human-readable intent for editor UX and exported provider config.
 */
description?: string | null; 
/**
 * The shell command to run
 */
command: string }
/**
 * Which lifecycle event triggers a hook.
 */
export type HookTrigger = "SessionStart" | "UserPromptSubmit" | "PreToolUse" | "PermissionRequest" | "PostToolUse" | "PostToolUseFailure" | "Notification" | "SubagentStart" | "Stop" | "SubagentStop" | "PreCompact" | "BeforeTool" | "AfterTool" | "BeforeAgent" | "AfterAgent" | "SessionEnd" | "BeforeModel" | "AfterModel" | "BeforeToolSelection"
export type LogEntry = { timestamp: string; actor: string; action: string; details: string }
export type McpDiscoveredTool = { name: string; description?: string | null }
export type McpProbeReport = { 
/**
 * Unix epoch seconds.
 */
generated_at: string; checked_servers: number; reachable_servers: number; discovered_tools: number; results: McpProbeServerReport[] }
export type McpProbeServerReport = { server_id: string; server_name: string; 
/**
 * "stdio" | "http" | "sse"
 */
transport: string; ok: boolean; 
/**
 * "ready" | "needs-attention" | "disabled" | "partial"
 */
status: string; message?: string | null; warnings?: string[]; discovered_tools?: McpDiscoveredTool[]; duration_ms: number }
export type McpRegistryEntry = { id: string; server_name: string; title: string; description: string; version: string; 
/**
 * "stdio" | "http" | "sse"
 */
transport: string; command: string | null; args: string[]; url: string | null; required_env: string[]; required_headers: string[]; source_url: string | null; website_url: string | null }
export type McpServerConfig = { id?: string; name: string; 
/**
 * For stdio servers: the binary to run
 */
command: string; args?: string[]; env?: Partial<{ [key in string]: string }>; 
/**
 * "global" | "project" | "mode"
 */
scope?: string; 
/**
 * Transport type: stdio (default), sse, or http
 */
server_type?: McpServerType; 
/**
 * URL for SSE or HTTP servers (ignored for stdio)
 */
url: string | null; 
/**
 * If true, the server is registered but not started
 */
disabled?: boolean; 
/**
 * Optional connection timeout in seconds
 */
timeout_secs: number | null }
export type McpServerType = "stdio" | "sse" | "http"
export type McpValidationIssue = { level: string; code: string; message: string; hint?: string | null; server_id?: string | null; provider_id?: string | null; source_path?: string | null }
export type McpValidationReport = { ok: boolean; checked_servers: number; checked_provider_configs: number; issues: McpValidationIssue[] }
export type ModeConfig = { id: string; name: string; description?: string | null; 
/**
 * Tool IDs visible in this mode (empty = all)
 */
active_tools?: string[]; 
/**
 * MCP server IDs active in this mode (empty = all)
 */
mcp_servers?: string[]; 
/**
 * Skill IDs active in this mode (empty = all)
 */
skills?: string[]; 
/**
 * Rule IDs active in this mode (empty = all). Rule IDs map to rule file
 * names without the `.md` suffix.
 */
rules?: string[]; 
/**
 * Legacy field name for mode-level instruction skill selection.
 * This now references a skill ID.
 */
prompt_id?: string | null; 
/**
 * Hooks to apply when this mode is active
 */
hooks?: HookConfig[]; 
/**
 * Permission overrides for this mode
 */
permissions?: PermissionConfig; 
/**
 * Which agent targets to sync to (e.g. ["claude", "gemini"])
 */
target_agents?: string[] }
/**
 * Serializable model info for Tauri/MCP.
 */
export type ModelInfo = { id: string; name: string; provider_id: string; context_window: number; recommended: boolean }
export type NamespaceConfig = { 
/**
 * Stable namespace id (e.g. "project", "agents", "generated", "plugin:ghost-issues")
 */
id: string; 
/**
 * Directory path relative to `.ship/`
 */
path: string; 
/**
 * Owning module or family (e.g. "project", "agents", "runtime", "plugins")
 */
owner: string }
export type NetworkPermissions = { policy?: NetworkPolicy; allow_hosts?: string[] }
export type NetworkPolicy = "none" | "localhost" | "allow-list" | "unrestricted"
export type NoteDocument = { id: string; title: string; updated: string; content: string }
export type NoteInfo = { id: string; title: string; updated: string }
/**
 * Mode-scoped tool permission overrides.
 * These overlay canonical `.ship/agents/permissions.toml` `tools.allow/deny`
 * when a mode is active.
 */
export type PermissionConfig = { allow?: string[]; deny?: string[] }
export type Permissions = { tools?: ToolPermissions; filesystem?: FsPermissions; commands?: CommandPermissions; network?: NetworkPermissions; agent?: AgentLimits }
export type ProjectConfig = { version?: string; 
/**
 * Stable project identity. Generated on `ship init`, used as the SQLite state directory key.
 * Never changes after creation — rename the project by changing `name`, not `id`.
 */
id?: string; name: string | null; description: string | null; statuses?: StatusConfig[]; git?: GitConfig; ai: AiConfig | null; modes: ModeConfig[]; mcp_servers: McpServerConfig[]; active_mode?: string | null; 
/**
 * Global hooks applied regardless of active mode
 */
hooks: HookConfig[]; agent: AgentLayerConfig; 
/**
 * Which agent providers to generate config for on branch checkout.
 * Alpha: "claude" | "gemini" | "codex". Defaults to ["claude"].
 */
providers: string[]; 
/**
 * Claimed `.ship` namespaces. First-party modules are always present.
 */
namespaces?: NamespaceConfig[] }
export type ProjectDiscovery = { name: string; 
/**
 * Stored as PathBuf internally; serialized as a string path on the wire.
 */
path: string }
export type ProjectInfo = { name: string; path: string }
export type ProviderImportReport = { imported_mcp_servers: number; imported_skills: number; imported_permissions: boolean }
/**
 * Serializable projection of `ProviderDescriptor` for MCP tools and Tauri commands.
 */
export type ProviderInfo = { id: string; name: string; binary: string; project_config: string; global_config: string; config_format: string; prompt_output: string; skills_output: string; 
/**
 * True when this provider is listed in the project's `providers` field.
 */
enabled: boolean; 
/**
 * True when the provider's binary is found in PATH.
 */
installed: boolean; 
/**
 * Version string from `<binary> --version`, if the binary is installed.
 */
version: string | null; 
/**
 * Known models for this provider.
 */
models: ModelInfo[] }
export type ProviderToolVocabularyEntry = { provider_id: string; provider_name: string; enabled: boolean; installed: boolean; tool_ids: string[] }
export type ReleaseDocument = { id: string; file_name: string; version: string; status: string; path: string; updated: string; content: string }
export type ReleaseInfo = { id: string; file_name: string; version: string; status: string; path: string; updated: string }
/**
 * A rule file from `agents/rules/*.md`. Rules are always active for the agent.
 */
export type Rule = { file_name: string; path: string; content: string }
export type RuntimePerfSnapshot = { terminal_start_calls: number; terminal_start_errors: number; terminal_start_last_micros: number; terminal_read_calls: number; terminal_read_bytes: number; terminal_read_errors: number; terminal_last_read_micros: number; terminal_write_calls: number; terminal_write_errors: number; terminal_write_last_micros: number; terminal_resize_calls: number; terminal_resize_errors: number; terminal_resize_last_micros: number; terminal_stop_calls: number; terminal_stop_errors: number; terminal_stop_last_micros: number; watcher_fs_events: number; watcher_flushes: number; watcher_ingest_runs: number; watcher_last_ingest_micros: number }
/**
 * Typed push events from the backend to the UI.
 * Each variant maps to a `{ type: "..." }` payload on the TypeScript side.
 */
export type ShipEvent = 
/**
 * ADR files changed.
 */
{ type: "adrs-changed" } | 
/**
 * Feature files changed.
 */
{ type: "features-changed" } | 
/**
 * Release files changed.
 */
{ type: "releases-changed" } | 
/**
 * Project config (ship.toml) changed.
 */
{ type: "config-changed" } | 
/**
 * Event log changed (new events ingested).
 */
{ type: "events-changed" } | 
/**
 * Human-readable log changed.
 */
{ type: "log-changed" } | 
/**
 * Note files or DB entries changed.
 */
{ type: "notes-changed" }
export type ShipWorkspaceKind = "feature" | "patch" | "service"
/**
 * A callable slash command / skill (→ `.claude/commands/<id>.md`).
 * Skills are the canonical instruction primitive in Ship.
 * They can be invoked explicitly by the user with `/skill-name [args]`
 * and can use `$ARGUMENTS`.
 * Stored as:
 * - project scope: `.ship/agents/skills/<id>/SKILL.md`
 * - user scope: `~/.ship/skills/<id>/SKILL.md`
 * using Agent Skills spec format.
 */
export type Skill = { id: string; name: string; description?: string | null; version?: string | null; author?: string | null; 
/**
 * The command template. Use `$ARGUMENTS` as a placeholder for user input.
 */
content: string; source?: SkillSource }
/**
 * Origin of a skill document.
 */
export type SkillSource = "custom" | "builtin" | "ai-generated" | "community" | "imported"
export type SkillToolHint = { id: string; name: string; allowed_tools: string[] }
export type StatusConfig = { id: string; name: string; color?: string }
export type ToolPermissions = { allow?: string[]; deny?: string[] }
export type VisionDocument = { content: string }
/**
 * Workspace runtime state — SQLite only, no frontmatter file.
 * `branch` is the workspace key and can represent either a git branch or a
 * non-git runtime workspace identifier.
 */
export type Workspace = { id: string; branch: string; workspace_type?: ShipWorkspaceKind; status?: WorkspaceStatus; environment_id?: string | null; feature_id?: string | null; target_id?: string | null; active_mode?: string | null; providers?: string[]; mcp_servers?: string[]; skills?: string[]; resolved_at: string; last_activated_at?: string | null; is_worktree: boolean; worktree_path?: string | null; context_hash?: string | null; config_generation?: number; compiled_at?: string | null; compile_error?: string | null }
export type WorkspaceAgentOverridesInput = { providers: string[] | null; mcpServers: string[] | null; skills: string[] | null }
export type WorkspaceEditorInfo = { id: string; name: string; binary: string }
export type WorkspaceFileChange = { status: string; path: string }
export type WorkspaceGitStatusSummary = { branch: string; touched_files: number; insertions: number; deletions: number; ahead: number; behind: number; upstream?: string | null }
export type WorkspaceProviderMatrix = { workspace_branch: string; mode_id?: string | null; source: string; allowed_providers: string[]; supported_providers: string[]; resolution_error?: string | null }
export type WorkspaceRepairReport = { workspace_branch: string; dry_run: boolean; mode_id?: string | null; status: WorkspaceStatus; providers_expected: string[]; missing_provider_configs: string[]; had_compile_error: boolean; needs_recompile: boolean; reapplied_compile: boolean; resolution_error?: string | null; actions: string[] }
export type WorkspaceSession = { id: string; workspace_id: string; workspace_branch: string; status: WorkspaceSessionStatus; started_at: string; ended_at?: string | null; mode_id?: string | null; primary_provider?: string | null; goal?: string | null; summary?: string | null; updated_feature_ids?: string[]; session_record_id?: string | null; compiled_at?: string | null; compile_error?: string | null; config_generation_at_start?: number | null; stale_context?: boolean; created_at: string; updated_at: string }
export type WorkspaceSessionStatus = "active" | "ended"
export type WorkspaceStatus = "active" | "archived"
export type WorkspaceTerminalSessionInfo = { session_id: string; branch: string; provider: string; cwd: string; cols: number; rows: number; activation_error?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
