/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSettingsRouteImport } from './routes/project/settings'
import { Route as ProjectReleasesRouteImport } from './routes/project/releases'
import { Route as ProjectOverviewRouteImport } from './routes/project/overview'
import { Route as ProjectNotesRouteImport } from './routes/project/notes'
import { Route as ProjectFeaturesRouteImport } from './routes/project/features'
import { Route as ProjectAgentsRouteImport } from './routes/project/agents'
import { Route as ProjectAdrsRouteImport } from './routes/project/adrs'
import { Route as ProjectActivityRouteImport } from './routes/project/activity'
import { Route as ProjectWorkflowWorkspaceRouteImport } from './routes/project/workflow.workspace'
import { Route as ProjectAgentsV0RouteImport } from './routes/project/agents.v0'
import { Route as ProjectAgentsSkillsRouteImport } from './routes/project/agents.skills'
import { Route as ProjectAgentsRulesRouteImport } from './routes/project/agents.rules'
import { Route as ProjectAgentsProvidersRouteImport } from './routes/project/agents.providers'
import { Route as ProjectAgentsPermissionsRouteImport } from './routes/project/agents.permissions'
import { Route as ProjectAgentsMcpRouteImport } from './routes/project/agents.mcp'
import { Route as ProjectAgentsHooksRouteImport } from './routes/project/agents.hooks'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSettingsRoute = ProjectSettingsRouteImport.update({
  id: '/project/settings',
  path: '/project/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectReleasesRoute = ProjectReleasesRouteImport.update({
  id: '/project/releases',
  path: '/project/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectOverviewRoute = ProjectOverviewRouteImport.update({
  id: '/project/overview',
  path: '/project/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNotesRoute = ProjectNotesRouteImport.update({
  id: '/project/notes',
  path: '/project/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectFeaturesRoute = ProjectFeaturesRouteImport.update({
  id: '/project/features',
  path: '/project/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectAgentsRoute = ProjectAgentsRouteImport.update({
  id: '/project/agents',
  path: '/project/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectAdrsRoute = ProjectAdrsRouteImport.update({
  id: '/project/adrs',
  path: '/project/adrs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectActivityRoute = ProjectActivityRouteImport.update({
  id: '/project/activity',
  path: '/project/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectWorkflowWorkspaceRoute =
  ProjectWorkflowWorkspaceRouteImport.update({
    id: '/project/workflow/workspace',
    path: '/project/workflow/workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectAgentsV0Route = ProjectAgentsV0RouteImport.update({
  id: '/v0',
  path: '/v0',
  getParentRoute: () => ProjectAgentsRoute,
} as any)
const ProjectAgentsSkillsRoute = ProjectAgentsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ProjectAgentsRoute,
} as any)
const ProjectAgentsRulesRoute = ProjectAgentsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => ProjectAgentsRoute,
} as any)
const ProjectAgentsProvidersRoute = ProjectAgentsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => ProjectAgentsRoute,
} as any)
const ProjectAgentsPermissionsRoute =
  ProjectAgentsPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => ProjectAgentsRoute,
  } as any)
const ProjectAgentsMcpRoute = ProjectAgentsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ProjectAgentsRoute,
} as any)
const ProjectAgentsHooksRoute = ProjectAgentsHooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => ProjectAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/project/activity': typeof ProjectActivityRoute
  '/project/adrs': typeof ProjectAdrsRoute
  '/project/agents': typeof ProjectAgentsRouteWithChildren
  '/project/features': typeof ProjectFeaturesRoute
  '/project/notes': typeof ProjectNotesRoute
  '/project/overview': typeof ProjectOverviewRoute
  '/project/releases': typeof ProjectReleasesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/agents/hooks': typeof ProjectAgentsHooksRoute
  '/project/agents/mcp': typeof ProjectAgentsMcpRoute
  '/project/agents/permissions': typeof ProjectAgentsPermissionsRoute
  '/project/agents/providers': typeof ProjectAgentsProvidersRoute
  '/project/agents/rules': typeof ProjectAgentsRulesRoute
  '/project/agents/skills': typeof ProjectAgentsSkillsRoute
  '/project/agents/v0': typeof ProjectAgentsV0Route
  '/project/workflow/workspace': typeof ProjectWorkflowWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/project/activity': typeof ProjectActivityRoute
  '/project/adrs': typeof ProjectAdrsRoute
  '/project/agents': typeof ProjectAgentsRouteWithChildren
  '/project/features': typeof ProjectFeaturesRoute
  '/project/notes': typeof ProjectNotesRoute
  '/project/overview': typeof ProjectOverviewRoute
  '/project/releases': typeof ProjectReleasesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/agents/hooks': typeof ProjectAgentsHooksRoute
  '/project/agents/mcp': typeof ProjectAgentsMcpRoute
  '/project/agents/permissions': typeof ProjectAgentsPermissionsRoute
  '/project/agents/providers': typeof ProjectAgentsProvidersRoute
  '/project/agents/rules': typeof ProjectAgentsRulesRoute
  '/project/agents/skills': typeof ProjectAgentsSkillsRoute
  '/project/agents/v0': typeof ProjectAgentsV0Route
  '/project/workflow/workspace': typeof ProjectWorkflowWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/project/activity': typeof ProjectActivityRoute
  '/project/adrs': typeof ProjectAdrsRoute
  '/project/agents': typeof ProjectAgentsRouteWithChildren
  '/project/features': typeof ProjectFeaturesRoute
  '/project/notes': typeof ProjectNotesRoute
  '/project/overview': typeof ProjectOverviewRoute
  '/project/releases': typeof ProjectReleasesRoute
  '/project/settings': typeof ProjectSettingsRoute
  '/project/agents/hooks': typeof ProjectAgentsHooksRoute
  '/project/agents/mcp': typeof ProjectAgentsMcpRoute
  '/project/agents/permissions': typeof ProjectAgentsPermissionsRoute
  '/project/agents/providers': typeof ProjectAgentsProvidersRoute
  '/project/agents/rules': typeof ProjectAgentsRulesRoute
  '/project/agents/skills': typeof ProjectAgentsSkillsRoute
  '/project/agents/v0': typeof ProjectAgentsV0Route
  '/project/workflow/workspace': typeof ProjectWorkflowWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/project/activity'
    | '/project/adrs'
    | '/project/agents'
    | '/project/features'
    | '/project/notes'
    | '/project/overview'
    | '/project/releases'
    | '/project/settings'
    | '/project/agents/hooks'
    | '/project/agents/mcp'
    | '/project/agents/permissions'
    | '/project/agents/providers'
    | '/project/agents/rules'
    | '/project/agents/skills'
    | '/project/agents/v0'
    | '/project/workflow/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/project/activity'
    | '/project/adrs'
    | '/project/agents'
    | '/project/features'
    | '/project/notes'
    | '/project/overview'
    | '/project/releases'
    | '/project/settings'
    | '/project/agents/hooks'
    | '/project/agents/mcp'
    | '/project/agents/permissions'
    | '/project/agents/providers'
    | '/project/agents/rules'
    | '/project/agents/skills'
    | '/project/agents/v0'
    | '/project/workflow/workspace'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/project/activity'
    | '/project/adrs'
    | '/project/agents'
    | '/project/features'
    | '/project/notes'
    | '/project/overview'
    | '/project/releases'
    | '/project/settings'
    | '/project/agents/hooks'
    | '/project/agents/mcp'
    | '/project/agents/permissions'
    | '/project/agents/providers'
    | '/project/agents/rules'
    | '/project/agents/skills'
    | '/project/agents/v0'
    | '/project/workflow/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectActivityRoute: typeof ProjectActivityRoute
  ProjectAdrsRoute: typeof ProjectAdrsRoute
  ProjectAgentsRoute: typeof ProjectAgentsRouteWithChildren
  ProjectFeaturesRoute: typeof ProjectFeaturesRoute
  ProjectNotesRoute: typeof ProjectNotesRoute
  ProjectOverviewRoute: typeof ProjectOverviewRoute
  ProjectReleasesRoute: typeof ProjectReleasesRoute
  ProjectSettingsRoute: typeof ProjectSettingsRoute
  ProjectWorkflowWorkspaceRoute: typeof ProjectWorkflowWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/settings': {
      id: '/project/settings'
      path: '/project/settings'
      fullPath: '/project/settings'
      preLoaderRoute: typeof ProjectSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/releases': {
      id: '/project/releases'
      path: '/project/releases'
      fullPath: '/project/releases'
      preLoaderRoute: typeof ProjectReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/overview': {
      id: '/project/overview'
      path: '/project/overview'
      fullPath: '/project/overview'
      preLoaderRoute: typeof ProjectOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/notes': {
      id: '/project/notes'
      path: '/project/notes'
      fullPath: '/project/notes'
      preLoaderRoute: typeof ProjectNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/features': {
      id: '/project/features'
      path: '/project/features'
      fullPath: '/project/features'
      preLoaderRoute: typeof ProjectFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/agents': {
      id: '/project/agents'
      path: '/project/agents'
      fullPath: '/project/agents'
      preLoaderRoute: typeof ProjectAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/adrs': {
      id: '/project/adrs'
      path: '/project/adrs'
      fullPath: '/project/adrs'
      preLoaderRoute: typeof ProjectAdrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/activity': {
      id: '/project/activity'
      path: '/project/activity'
      fullPath: '/project/activity'
      preLoaderRoute: typeof ProjectActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/workflow/workspace': {
      id: '/project/workflow/workspace'
      path: '/project/workflow/workspace'
      fullPath: '/project/workflow/workspace'
      preLoaderRoute: typeof ProjectWorkflowWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/agents/v0': {
      id: '/project/agents/v0'
      path: '/v0'
      fullPath: '/project/agents/v0'
      preLoaderRoute: typeof ProjectAgentsV0RouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
    '/project/agents/skills': {
      id: '/project/agents/skills'
      path: '/skills'
      fullPath: '/project/agents/skills'
      preLoaderRoute: typeof ProjectAgentsSkillsRouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
    '/project/agents/rules': {
      id: '/project/agents/rules'
      path: '/rules'
      fullPath: '/project/agents/rules'
      preLoaderRoute: typeof ProjectAgentsRulesRouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
    '/project/agents/providers': {
      id: '/project/agents/providers'
      path: '/providers'
      fullPath: '/project/agents/providers'
      preLoaderRoute: typeof ProjectAgentsProvidersRouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
    '/project/agents/permissions': {
      id: '/project/agents/permissions'
      path: '/permissions'
      fullPath: '/project/agents/permissions'
      preLoaderRoute: typeof ProjectAgentsPermissionsRouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
    '/project/agents/mcp': {
      id: '/project/agents/mcp'
      path: '/mcp'
      fullPath: '/project/agents/mcp'
      preLoaderRoute: typeof ProjectAgentsMcpRouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
    '/project/agents/hooks': {
      id: '/project/agents/hooks'
      path: '/hooks'
      fullPath: '/project/agents/hooks'
      preLoaderRoute: typeof ProjectAgentsHooksRouteImport
      parentRoute: typeof ProjectAgentsRoute
    }
  }
}

interface ProjectAgentsRouteChildren {
  ProjectAgentsHooksRoute: typeof ProjectAgentsHooksRoute
  ProjectAgentsMcpRoute: typeof ProjectAgentsMcpRoute
  ProjectAgentsPermissionsRoute: typeof ProjectAgentsPermissionsRoute
  ProjectAgentsProvidersRoute: typeof ProjectAgentsProvidersRoute
  ProjectAgentsRulesRoute: typeof ProjectAgentsRulesRoute
  ProjectAgentsSkillsRoute: typeof ProjectAgentsSkillsRoute
  ProjectAgentsV0Route: typeof ProjectAgentsV0Route
}

const ProjectAgentsRouteChildren: ProjectAgentsRouteChildren = {
  ProjectAgentsHooksRoute: ProjectAgentsHooksRoute,
  ProjectAgentsMcpRoute: ProjectAgentsMcpRoute,
  ProjectAgentsPermissionsRoute: ProjectAgentsPermissionsRoute,
  ProjectAgentsProvidersRoute: ProjectAgentsProvidersRoute,
  ProjectAgentsRulesRoute: ProjectAgentsRulesRoute,
  ProjectAgentsSkillsRoute: ProjectAgentsSkillsRoute,
  ProjectAgentsV0Route: ProjectAgentsV0Route,
}

const ProjectAgentsRouteWithChildren = ProjectAgentsRoute._addFileChildren(
  ProjectAgentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectActivityRoute: ProjectActivityRoute,
  ProjectAdrsRoute: ProjectAdrsRoute,
  ProjectAgentsRoute: ProjectAgentsRouteWithChildren,
  ProjectFeaturesRoute: ProjectFeaturesRoute,
  ProjectNotesRoute: ProjectNotesRoute,
  ProjectOverviewRoute: ProjectOverviewRoute,
  ProjectReleasesRoute: ProjectReleasesRoute,
  ProjectSettingsRoute: ProjectSettingsRoute,
  ProjectWorkflowWorkspaceRoute: ProjectWorkflowWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
