packages:
  - "apps/docs"
  - "apps/web"
  - "packages/*"

enableGlobalVirtualStore: false

ignoredBuiltDependencies:
  - esbuild
  - lightningcss

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lightningcss
  - workerd
