//! MCP tool pre-approval for each provider.
//!
//! After compilation, `ship use` pre-approves the ship-mcp server tools in
//! each provider's global or project-local settings so the user is not
//! prompted on every session start.

use anyhow::{Context, Result};

use super::output::ensure_parent;

// ── Generic JSON helpers ─────────────────────────────────────────────────────

/// Ensure a JSON pattern is in an array at the given JSON pointer path.
/// Creates intermediate objects if needed. Returns Ok(false) if already present.
pub(crate) fn ensure_json_array_entry(
    settings: &mut serde_json::Value,
    pointer_parts: &[&str],
    pattern: &str,
) -> Result<bool> {
    // Check if already present
    let pointer = format!("/{}", pointer_parts.join("/"));
    let already_present = settings
        .pointer(&pointer)
        .and_then(|v| v.as_array())
        .is_some_and(|arr| arr.iter().any(|v| v.as_str() == Some(pattern)));
    if already_present {
        return Ok(false);
    }

    // Navigate/create path to the array
    let mut current = settings.as_object_mut().context("root must be object")?;
    for &part in &pointer_parts[..pointer_parts.len() - 1] {
        let entry = current.entry(part).or_insert(serde_json::json!({}));
        current = entry
            .as_object_mut()
            .context("intermediate must be object")?;
    }
    let last = pointer_parts.last().context("empty path")?;
    let arr_val = current.entry(*last).or_insert(serde_json::json!([]));
    let arr = arr_val.as_array_mut().context("leaf must be array")?;
    arr.push(serde_json::json!(pattern));
    Ok(true)
}

/// Read-modify-write a JSON settings file. Calls `mutate` to apply changes.
/// Creates the file and parent dirs if they don't exist.
fn update_json_settings(
    path: &std::path::Path,
    mutate: impl FnOnce(&mut serde_json::Value) -> Result<bool>,
) -> Result<()> {
    ensure_parent(path)?;
    let mut settings: serde_json::Value = if path.exists() {
        serde_json::from_str(&std::fs::read_to_string(path)?).unwrap_or(serde_json::json!({}))
    } else {
        serde_json::json!({})
    };
    if mutate(&mut settings)? {
        std::fs::write(path, serde_json::to_string_pretty(&settings)?)?;
    }
    Ok(())
}

// ── Provider-specific allow-listing ──────────────────────────────────────────

/// Claude: write `mcp__ship__*` to `~/.claude/settings.json` permissions.allow.
pub(crate) fn ensure_ship_mcp_allowed_claude() -> Result<()> {
    let path = dirs::home_dir()
        .context("could not determine home directory")?
        .join(".claude")
        .join("settings.json");
    update_json_settings(&path, |s| {
        ensure_json_array_entry(s, &["permissions", "allow"], "mcp__ship__*")
    })
}

/// Gemini: write allow policy for ship MCP to `~/.gemini/policies/ship-mcp.toml`.
pub(crate) fn ensure_ship_mcp_allowed_gemini() -> Result<()> {
    let path = dirs::home_dir()
        .context("could not determine home directory")?
        .join(".gemini")
        .join("policies")
        .join("ship-mcp.toml");
    ensure_parent(&path)?;

    let content = r#"# Generated by Ship. Pre-approves ship MCP tools globally.

[[tool_policies]]
tool = "mcp"
pattern = "ship/.*"
decision = "allow"
"#;

    // Idempotent — only write if missing or different
    if path.exists() {
        let existing = std::fs::read_to_string(&path)?;
        if existing == content {
            return Ok(());
        }
    }
    std::fs::write(&path, content)?;
    Ok(())
}

/// Cursor: write `Mcp(ship:*)` to project `.cursor/cli.json` permissions.allow.
pub(crate) fn ensure_ship_mcp_allowed_cursor(project_root: &std::path::Path) -> Result<()> {
    let path = project_root.join(".cursor").join("cli.json");
    update_json_settings(&path, |s| {
        // Ensure version field exists
        if s.get("version").is_none() {
            s["version"] = serde_json::json!(1);
        }
        ensure_json_array_entry(s, &["permissions", "allow"], "Mcp(ship:*)")
    })
}
