/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CompilerRouteImport } from './routes/compiler'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevJobsRouteImport } from './routes/dev/jobs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CompilerRoute = CompilerRouteImport.update({
  id: '/compiler',
  path: '/compiler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevJobsRoute = DevJobsRouteImport.update({
  id: '/dev/jobs',
  path: '/dev/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compiler': typeof CompilerRoute
  '/studio': typeof StudioRoute
  '/dev/jobs': typeof DevJobsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compiler': typeof CompilerRoute
  '/studio': typeof StudioRoute
  '/dev/jobs': typeof DevJobsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compiler': typeof CompilerRoute
  '/studio': typeof StudioRoute
  '/dev/jobs': typeof DevJobsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compiler' | '/studio' | '/dev/jobs' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compiler' | '/studio' | '/dev/jobs' | '/api/auth/$'
  id: '__root__' | '/' | '/compiler' | '/studio' | '/dev/jobs' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompilerRoute: typeof CompilerRoute
  StudioRoute: typeof StudioRoute
  DevJobsRoute: typeof DevJobsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiler': {
      id: '/compiler'
      path: '/compiler'
      fullPath: '/compiler'
      preLoaderRoute: typeof CompilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/jobs': {
      id: '/dev/jobs'
      path: '/dev/jobs'
      fullPath: '/dev/jobs'
      preLoaderRoute: typeof DevJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompilerRoute: CompilerRoute,
  StudioRoute: StudioRoute,
  DevJobsRoute: DevJobsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
