//! `ship init` — scaffold .ship/ in a project or configure ~/.ship/ globally.

use anyhow::Result;

use crate::paths;

pub fn run(global: bool, provider: Option<String>) -> Result<()> {
    if global {
        run_global()
    } else {
        run_project(provider)
    }
}

fn run_global() -> Result<()> {
    paths::ensure_global_dirs()?;
    let cfg_path = paths::global_dir().join("config.toml");
    if !cfg_path.exists() {
        std::fs::write(
            &cfg_path,
            "# Ship global configuration\n\n[identity]\nname = \"\"\n",
        )?;
    }
    let readme = paths::global_dir().join("README.md");
    if !readme.exists() {
        std::fs::write(
            &readme,
            "# Ship\n\nPersonal AI agent configuration. See https://getship.dev\n",
        )?;
    }
    println!("initialized global config at ~/.ship/");
    println!("  Edit ~/.ship/config.toml to set your identity");
    Ok(())
}

fn run_project(provider: Option<String>) -> Result<()> {
    paths::ensure_project_dirs()?;
    let ship_jsonc = paths::project_ship_jsonc();
    let ship_toml = paths::project_ship_toml();
    // Scaffold .ship/ship.jsonc when no config exists (prefer JSONC over TOML)
    if !ship_jsonc.exists() && !ship_toml.exists() {
        let provider_str = provider.as_deref().unwrap_or("claude");
        std::fs::write(
            &ship_jsonc,
            format!(
r#"{{
  // Ship project configuration — https://getship.dev
  "$schema": "../schemas/ship.schema.json",
  "project": {{
    "providers": ["{provider_str}"],
  }},
}}"#
            ),
        )?;
    }
    let gitignore = paths::project_dir().join(".gitignore");
    if !gitignore.exists() {
        std::fs::write(
            &gitignore,
            "# Ship — compiled artifacts (regenerated by ship use)\n\
             /secrets/\nCLAUDE.md\nGEMINI.md\nAGENTS.md\n.mcp.json\n.codex/\n.gemini/\n.cursor/\n",
        )?;
    }
    let readme = paths::project_dir().join("README.md");
    if !readme.exists() {
        std::fs::write(
            &readme,
            "# Ship Configuration\n\nThis project uses [Ship](https://getship.dev) \
             to manage AI agent configuration.\n\n\
             Install the CLI: `curl -fsSL https://getship.dev/install | sh`\n\
             Then: `ship use <agent-id>` to activate.\n",
        )?;
    }
    println!("initialized .ship/ in current directory");
    println!("  providers: {}", provider.as_deref().unwrap_or("claude"));
    println!("\nNext steps:");
    println!("  ship use <agent-id>     activate an agent (compiles immediately)");
    println!("  ship compile            re-compile current agent");
    Ok(())
}
