mod agent;
mod auth;
mod cli;
mod compile;
mod config;
mod job;
mod loader;
mod mcp;
mod mode;
mod paths;
mod permissions;
mod profile;
mod skill;

use anyhow::Result;
use cli::{AgentCommands, Cli, Commands, JobCommands, McpCommands, ModeCommands, PermissionsCommands, SkillCommands};
use std::path::PathBuf;

fn main() -> Result<()> {
    use clap::Parser;
    let cli = Cli::parse();
    dispatch(cli.command)
}

fn dispatch(command: Option<Commands>) -> Result<()> {
    match command {
        None => run_status(None),
        Some(cmd) => match cmd {
            Commands::Init { global, provider, force } => run_init(global, provider, force),
            Commands::Login  => auth::run_login(),
            Commands::Logout => auth::run_logout(),
            Commands::Whoami => auth::run_whoami(),
            Commands::Use { mode, path, compile: _ } => run_use(Some(&mode), path),
            Commands::Status { path } => run_status(path),
            Commands::Modes { local, project, cloud } => run_modes(local, project, cloud),
            Commands::Mode { action } => dispatch_mode(action),
            Commands::Compile { provider, dry_run, watch, path } => {
                run_compile_cmd(provider.as_deref(), dry_run, watch, path)
            }
            Commands::Skill { action } => dispatch_skill(action),
            Commands::Mcp { action } => dispatch_mcp(action),
            Commands::Import { path } => {
                stub("import", &format!("Would import from {:?}", path.as_deref().unwrap_or(std::path::Path::new("."))))
            }
            Commands::Export { provider, zip: _ } => {
                run_compile_cmd(Some(&provider), false, false, None)
            }
            Commands::Sync { pull: _, push: _ } => {
                stub("sync", "Cloud sync requires a Ship account. Run: ship login")
            }
            Commands::Server { .. } => {
                stub("server", "Local server (port 7701) — coming soon")
            }
            Commands::Next { worktrees_dir } => job::next(worktrees_dir),
            Commands::Retry { id, worktrees_dir } => job::retry(&id, worktrees_dir),
            Commands::Gate { id, worktrees_dir } => job::gate(&id, worktrees_dir),
            Commands::Job { action } => dispatch_job(action),
            Commands::Permissions { action } => dispatch_permissions(action),
            Commands::Adrs => run_adrs(),
            Commands::Notes => run_notes(),
            Commands::Migrate => run_migrate(),
            Commands::Agent { action } => agent::dispatch_agent(action),
        },
    }
}

// ── Init ──────────────────────────────────────────────────────────────────────

fn run_init(global: bool, provider: Option<String>, force: bool) -> Result<()> {
    if global {
        paths::ensure_global_dirs()?;
        let cfg_path = paths::global_dir().join("config.toml");
        if !cfg_path.exists() || force {
            std::fs::write(&cfg_path, "# Ship Studio global configuration\n\n[identity]\nname = \"\"\n")?;
        }
        let readme = paths::global_dir().join("README.md");
        if !readme.exists() || force {
            std::fs::write(&readme, "# Ship\n\nPersonal AI agent configuration. See https://getship.dev\n")?;
        }
        println!("✓ initialized global config at ~/.ship/");
        println!("  Edit ~/.ship/config.toml to set your identity");
    } else {
        let cwd = std::env::current_dir()?;
        init_project(&cwd, provider.as_deref(), force)?;
    }
    Ok(())
}

/// Initialise a `.ship/` directory under `root`.
/// Extracted for testability — callers can pass a temp dir as `root`.
fn init_project(root: &std::path::Path, provider: Option<&str>, force: bool) -> Result<()> {
    let ship_dir = root.join(".ship");
    if ship_dir.exists() && !force {
        println!(".ship/ already exists. Use --force to overwrite existing config.");
        return Ok(());
    }

    let provider_str = provider.unwrap_or("claude");
    let mut created: Vec<String> = Vec::new();

    // Create directory structure
    for dir in [
        ship_dir.clone(),
        ship_dir.join("modes"),
        ship_dir.join("agents"),
        ship_dir.join("agents").join("rules"),
        ship_dir.join("agents").join("skills"),
        ship_dir.join("agents").join("profiles"),
        ship_dir.join("agents").join("presets"),
    ] {
        std::fs::create_dir_all(&dir)?;
    }

    // ship.toml
    let ship_toml = ship_dir.join("ship.toml");
    if !ship_toml.exists() || force {
        std::fs::write(&ship_toml, format!(
            "# Ship project configuration\n\n[defaults]\nprofile = \"default\"\nproviders = [\"{provider_str}\"]\n"
        ))?;
        created.push("ship.toml".to_string());
    }

    // .gitignore
    let gitignore = ship_dir.join(".gitignore");
    if !gitignore.exists() || force {
        std::fs::write(&gitignore,
            "# Ship — compiled artifacts (regenerated by ship use)\n\
             /secrets/\nCLAUDE.md\nGEMINI.md\nAGENTS.md\n.mcp.json\n.codex/\n.gemini/\n.cursor/\n"
        )?;
        created.push(".gitignore".to_string());
    }

    // agents/profiles/default.toml
    let default_profile = ship_dir.join("agents").join("profiles").join("default.toml");
    if !default_profile.exists() || force {
        std::fs::write(&default_profile, scaffold_default_profile(provider_str))?;
        created.push("agents/profiles/default.toml".to_string());
    }

    // agents/permissions.toml
    let permissions_path = ship_dir.join("agents").join("permissions.toml");
    if !permissions_path.exists() || force {
        std::fs::write(&permissions_path, scaffold_permissions_toml())?;
        created.push("agents/permissions.toml".to_string());
    }

    // agents/mcp.toml
    let mcp_path = ship_dir.join("agents").join("mcp.toml");
    if !mcp_path.exists() || force {
        std::fs::write(&mcp_path,
            "# Ship MCP server definitions\n\
             # Add servers with: ship mcp add <id> --url <url>\n\
             # or: ship mcp add-stdio <id> <command> [args...]\n\
             \n\
             # [[servers]]\n\
             # id = \"my-server\"\n\
             # command = \"npx\"\n\
             # args = [\"-y\", \"@mcp/my-server\"]\n"
        )?;
        created.push("agents/mcp.toml".to_string());
    }

    // README.md
    let readme = ship_dir.join("README.md");
    if !readme.exists() || force {
        std::fs::write(&readme,
            "# Ship Configuration\n\nThis project uses [Ship](https://getship.dev) \
             to manage AI agent configuration.\n\n\
             Install the CLI: `curl -fsSL https://getship.dev/install | sh`\n\
             Then: `ship use default` to activate.\n"
        )?;
        created.push("README.md".to_string());
    }

    println!("✓ initialized .ship/ in {}", root.display());
    for item in &created {
        println!("  created: {}", item);
    }
    println!("\nNext steps:");
    println!("  ship use default        activate the default profile");
    println!("  ship use <profile-id>   activate a custom profile");
    Ok(())
}

#[cfg(test)]
mod init_tests {
    use super::*;
    use tempfile::TempDir;

    fn tmp() -> TempDir { TempDir::new().unwrap() }

    #[test]
    fn init_creates_required_structure() {
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();

        let ship = dir.path().join(".ship");
        assert!(ship.exists(), ".ship/ must exist");
        assert!(ship.join("ship.toml").exists(), "ship.toml must exist");
        assert!(ship.join(".gitignore").exists(), ".gitignore must exist");
        assert!(ship.join("agents").join("profiles").join("default.toml").exists(),
                "agents/profiles/default.toml must exist");
        assert!(ship.join("agents").join("permissions.toml").exists(),
                "agents/permissions.toml must exist");
        assert!(ship.join("agents").join("mcp.toml").exists(),
                "agents/mcp.toml must exist");
        assert!(ship.join("agents").join("rules").is_dir(),
                "agents/rules/ must be a directory");
        assert!(ship.join("agents").join("skills").is_dir(),
                "agents/skills/ must be a directory");
    }

    #[test]
    fn init_default_profile_is_valid_toml() {
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();
        let path = dir.path().join(".ship").join("agents").join("profiles").join("default.toml");
        let content = std::fs::read_to_string(&path).unwrap();
        let profile: crate::mode::Profile = toml::from_str(&content)
            .expect("default.toml must parse as a valid Profile");
        assert_eq!(profile.meta.id, "default");
        assert_eq!(profile.meta.providers, vec!["claude"]);
        assert_eq!(profile.permissions.preset.as_deref(), Some("ship-standard"));
    }

    #[test]
    fn init_respects_provider_flag() {
        let dir = tmp();
        init_project(dir.path(), Some("gemini"), false).unwrap();
        let path = dir.path().join(".ship").join("agents").join("profiles").join("default.toml");
        let content = std::fs::read_to_string(&path).unwrap();
        let profile: crate::mode::Profile = toml::from_str(&content).unwrap();
        assert_eq!(profile.meta.providers, vec!["gemini"]);
    }

    #[test]
    fn init_twice_without_force_is_noop() {
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();

        // Overwrite the default profile with custom content
        let profile_path = dir.path().join(".ship").join("agents").join("profiles").join("default.toml");
        std::fs::write(&profile_path, "[profile]\nname=\"custom\"\nid=\"custom\"\n").unwrap();

        // Second init without --force should not overwrite
        init_project(dir.path(), None, false).unwrap();
        let after = std::fs::read_to_string(&profile_path).unwrap();
        assert!(after.contains("custom"), "second init must not overwrite existing files");
    }

    #[test]
    fn init_force_overwrites_existing() {
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();

        // Overwrite the default profile with custom content
        let profile_path = dir.path().join(".ship").join("agents").join("profiles").join("default.toml");
        std::fs::write(&profile_path, "[profile]\nname=\"custom\"\nid=\"custom\"\n").unwrap();

        // --force must regenerate
        init_project(dir.path(), None, true).unwrap();
        let after = std::fs::read_to_string(&profile_path).unwrap();
        assert!(after.contains("id = \"default\""), "--force must regenerate default.toml");
    }

    #[test]
    fn permissions_toml_has_named_presets() {
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();
        let path = dir.path().join(".ship").join("agents").join("permissions.toml");
        let content = std::fs::read_to_string(&path).unwrap();
        let val: toml::Value = toml::from_str(&content).unwrap();
        assert!(val.get("ship-standard").is_some(), "ship-standard preset required");
        assert!(val.get("ship-guarded").is_some(), "ship-guarded preset required");
        assert!(val.get("ship-open").is_some(), "ship-open preset required");
    }

    #[test]
    fn permissions_toml_preset_loadable_by_loader() {
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();
        let agents_dir = dir.path().join(".ship").join("agents");
        let preset = crate::loader::load_permission_preset(&agents_dir, "ship-standard");
        assert!(preset.is_some(), "ship-standard preset must be loadable via loader");
        let p = preset.unwrap();
        assert!(p.default_mode.is_some(), "ship-standard must have default_mode");
    }

    #[test]
    fn gitignore_does_not_contain_claude_md() {
        // CLAUDE.md is a generated artifact — must be gitignored, never committed
        let dir = tmp();
        init_project(dir.path(), None, false).unwrap();
        let gitignore = std::fs::read_to_string(
            dir.path().join(".ship").join(".gitignore")
        ).unwrap();
        assert!(gitignore.contains("CLAUDE.md"), ".gitignore must list CLAUDE.md");
    }
}

fn scaffold_default_profile(provider: &str) -> String {
    format!(
r#"[profile]
name = "default"
id = "default"
version = "0.1.0"
description = "Default Ship profile"
providers = ["{provider}"]

[skills]
# Skill IDs to activate (empty = all installed skills).
refs = []

[mcp]
# MCP server IDs to activate (empty = all configured servers).
servers = []

[permissions]
preset = "ship-standard"
# tools_deny = ["mcp__*__delete*"]
# tools_ask = ["Bash(rm -rf*)"]
# default_mode = "default"   # default | acceptEdits | plan | bypassPermissions

[rules]
# inline = """
# Keep operations deterministic.
# Run tests before marking work done.
# """
"#,
        provider = provider,
    )
}

fn scaffold_permissions_toml() -> &'static str {
    r#"# Ship permission presets
# Reference a preset in your profile: [permissions] preset = "ship-standard"

[ship-standard]
default_mode = "acceptEdits"
tools_ask = ["Bash(rm -rf*)", "Bash(*--force*)"]
tools_deny = ["Bash(git push --force*)"]

[ship-guarded]
default_mode = "default"
tools_ask = ["Bash(rm -rf*)", "Bash(*deploy*)"]
tools_deny = ["Bash(git push --force*)", "mcp__*__delete*", "mcp__*__drop*"]

[ship-open]
default_mode = "bypassPermissions"

[ship-plan]
default_mode = "plan"
"#
}

// ── Use ───────────────────────────────────────────────────────────────────────

/// Activate a profile: load → compile → install plugins → write ship.lock.
/// `profile_id = None` re-activates the current profile from ship.lock.
fn run_use(profile_id: Option<&str>, path: Option<PathBuf>) -> Result<()> {
    let project_root = path.as_deref()
        .map(std::fs::canonicalize)
        .transpose()?
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    if !project_root.join(".ship").exists() {
        anyhow::bail!(".ship/ not found. Run: ship init");
    }

    profile::activate_profile(profile_id, &project_root)
}

// ── Status ────────────────────────────────────────────────────────────────────

fn run_status(path: Option<PathBuf>) -> Result<()> {
    let target = path.as_deref()
        .map(std::fs::canonicalize)
        .transpose()?
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    let ship_dir = target.join(".ship");
    let lock = profile::ShipLock::load(&ship_dir);
    match lock.active_profile {
        Some(ref p) => {
            println!("active profile: {}", p);
            if let Some(ref at) = lock.compiled_at { println!("compiled: {}", at); }
            if !lock.plugins.installed.is_empty() {
                println!("plugins: {}", lock.plugins.installed.join(", "));
            }
        }
        None => {
            println!("No active profile for {}", target.display());
            println!("Run: ship use <profile-id>");
        }
    }
    Ok(())
}

// ── Modes / Profiles ──────────────────────────────────────────────────────────

fn run_modes(local: bool, project: bool, cloud: bool) -> Result<()> {
    if cloud {
        println!("Cloud profiles require a Ship account. Run: ship login");
        return Ok(());
    }
    let modes = paths::list_mode_ids(local, project);
    if modes.is_empty() {
        println!("No profiles found.");
        println!("Create one with: ship mode create <name>");
    } else {
        for (id, scope) in &modes {
            println!("  {} [{}]", id, scope);
        }
    }
    Ok(())
}

// ── Mode subcommands ──────────────────────────────────────────────────────────

fn dispatch_mode(action: ModeCommands) -> Result<()> {
    match action {
        ModeCommands::Create { name, global } => {
            let dir = if global { paths::global_modes_dir() } else { paths::project_presets_dir() };
            std::fs::create_dir_all(&dir)?;
            let path = dir.join(format!("{}.toml", name));
            if path.exists() {
                anyhow::bail!("Profile '{}' already exists at {}", name, path.display());
            }
            std::fs::write(&path, mode::Profile::scaffold(&name))?;
            println!("✓ created profile '{}' at {}", name, path.display());
        }
        ModeCommands::Edit { name, editor } => {
            let path = profile::find_profile_file(&name, &std::env::current_dir()?)
                .ok_or_else(|| anyhow::anyhow!("Profile '{}' not found", name))?;
            let editor = editor.or_else(|| std::env::var("EDITOR").ok()).unwrap_or_else(|| "vi".to_string());
            std::process::Command::new(&editor).arg(&path).status()?;
        }
        ModeCommands::Delete { name } => {
            let path = profile::find_profile_file(&name, &std::env::current_dir()?)
                .ok_or_else(|| anyhow::anyhow!("Profile '{}' not found", name))?;
            std::fs::remove_file(&path)?;
            println!("✓ deleted profile '{}'", name);
        }
        ModeCommands::Clone { source, target } => {
            let cwd = std::env::current_dir()?;
            let src_path = profile::find_profile_file(&source, &cwd)
                .ok_or_else(|| anyhow::anyhow!("Source profile '{}' not found", source))?;
            let dst_path = src_path.parent().unwrap().join(format!("{}.toml", target));
            if dst_path.exists() {
                anyhow::bail!("Target profile '{}' already exists", target);
            }
            let content = std::fs::read_to_string(&src_path)?
                .replace(&format!("id = \"{}\"", source), &format!("id = \"{}\"", target))
                .replace(&format!("name = \"{}\"", source), &format!("name = \"{}\"", target));
            std::fs::write(&dst_path, content)?;
            println!("✓ cloned '{}' → '{}'", source, target);
        }
        ModeCommands::Publish { name: _ } => {
            stub("mode publish", "Publishing requires a Ship account. Run: ship login")?;
        }
    }
    Ok(())
}

// ── Compile ───────────────────────────────────────────────────────────────────

fn run_compile_cmd(provider: Option<&str>, dry_run: bool, watch: bool, path: Option<PathBuf>) -> Result<()> {
    let project_root = path.as_deref()
        .map(std::fs::canonicalize).transpose()?
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    if !project_root.join(".ship").exists() {
        anyhow::bail!(".ship/ not found. Run: ship init");
    }

    let lock = profile::ShipLock::load(&project_root.join(".ship"));
    compile::run_compile(compile::CompileOptions {
        project_root: &project_root,
        provider,
        dry_run,
        active_mode: lock.active_profile.as_deref(),
    })?;

    if watch { println!("--watch not yet implemented. Run compile manually after changes."); }
    Ok(())
}

// ── Job subcommands ───────────────────────────────────────────────────────────

fn dispatch_job(action: JobCommands) -> Result<()> {
    match action {
        JobCommands::Create { kind, title, milestone, description, branch } => {
            job::create(&kind, &title, milestone.as_deref(), description.as_deref(), branch.as_deref())
        }
        JobCommands::List { status, branch, milestone } => {
            job::list(status.as_deref(), branch.as_deref(), milestone.as_deref())
        }
        JobCommands::Update { id, status } => job::update(&id, &status),
        JobCommands::Done { id } => job::done(&id),
    }
}

// ── Skill subcommands ─────────────────────────────────────────────────────────

fn dispatch_skill(action: SkillCommands) -> Result<()> {
    match action {
        SkillCommands::List => skill::list(),
        SkillCommands::Create { id, name, description } => skill::create(&id, name.as_deref(), description.as_deref()),
        SkillCommands::Remove { id, global } => skill::remove(&id, global),
        SkillCommands::Add { source, skill, global } => skill::add(&source, skill.as_deref(), global),
        SkillCommands::Update => stub("skill update", "Registry updates — coming soon"),
        SkillCommands::Validate { .. } => stub("skill validate", "Spec validation — coming soon"),
        SkillCommands::Publish { .. } => stub("skill publish", "Publishing requires a Ship account. Run: ship login"),
    }
}

// ── MCP subcommands ───────────────────────────────────────────────────────────

fn dispatch_mcp(action: McpCommands) -> Result<()> {
    match action {
        McpCommands::List => mcp::list(),
        McpCommands::Add { id, name, url, .. } => {
            let url = url.ok_or_else(|| anyhow::anyhow!("--url is required for HTTP/SSE servers"))?;
            mcp::add_http(&id, name, &url)
        }
        McpCommands::AddStdio { id, command, args, name, .. } => mcp::add_stdio(&id, name, &command, args),
        McpCommands::Remove { id } => mcp::remove(&id),
        McpCommands::Probe { id } => stub("mcp probe", &format!("Live probing for {:?} — requires local server", id)),
    }
}

// ── Permissions subcommands ───────────────────────────────────────────────────

fn dispatch_permissions(action: PermissionsCommands) -> Result<()> {
    match action {
        PermissionsCommands::Sync { path } => {
            let project_root = path.as_deref()
                .map(std::fs::canonicalize)
                .transpose()?
                .unwrap_or_else(|| std::env::current_dir().unwrap());
            if !project_root.join(".ship").exists() {
                anyhow::bail!(".ship/ not found. Run: ship init");
            }
            permissions::run_permissions_sync(&project_root)
        }
    }
}

// ── ADRs / Notes ──────────────────────────────────────────────────────────────

fn project_ship_dir() -> Result<std::path::PathBuf> {
    let cwd = std::env::current_dir()?;
    let ship_dir = cwd.join(".ship");
    if !ship_dir.exists() {
        anyhow::bail!(".ship/ not found in {}. Run: ship init", cwd.display());
    }
    Ok(ship_dir)
}

fn run_adrs() -> Result<()> {
    let ship_dir = project_ship_dir()?;
    let adrs = runtime::db::adrs::list_adrs(&ship_dir)?;
    if adrs.is_empty() {
        println!("No ADRs found.");
    } else {
        for entry in &adrs {
            println!("{}\t[{}]\t{}", entry.id, entry.status, entry.title);
        }
    }
    Ok(())
}

fn run_notes() -> Result<()> {
    let ship_dir = project_ship_dir()?;
    let notes = runtime::db::notes::list_notes(&ship_dir, None)?;
    if notes.is_empty() {
        println!("No notes found.");
    } else {
        for entry in &notes {
            println!("{}\t{}", entry.id, entry.title);
        }
    }
    Ok(())
}

fn run_migrate() -> Result<()> {
    let ship_dir = std::env::current_dir()?.join(".ship");
    if !ship_dir.exists() {
        anyhow::bail!(".ship/ not found. Run: ship init");
    }
    let report = runtime::db::migrate_from_state_db::migrate_notes_and_adrs(&ship_dir)?;
    println!("migration complete");
    println!("  notes:  {} migrated, {} skipped", report.notes_migrated, report.notes_skipped);
    println!("  adrs:   {} migrated, {} skipped", report.adrs_migrated, report.adrs_skipped);
    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn stub(command: &str, note: &str) -> Result<()> {
    println!("[{}] {}", command, note);
    Ok(())
}
