mod add;
mod agent;
mod cli;
mod compile;
mod config;
mod dep_skills;
mod install;
mod job;
mod loader;
mod mcp;
mod mode;
mod paths;
mod profile;
mod skill;
mod sync;

use anyhow::Result;
use cli::{AgentCommands, Cli, Commands, JobCommands, McpCommands, ModeCommands, PermissionsCommands, ProfileSyncCommands, SkillCommands};
use std::path::PathBuf;

fn main() -> Result<()> {
    use clap::Parser;
    let cli = Cli::parse();
    dispatch(cli.command)
}

fn dispatch(command: Option<Commands>) -> Result<()> {
    match command {
        None => run_status(None),
        Some(cmd) => match cmd {
            Commands::Init { global, provider, force: _ } => run_init(global, provider),
            Commands::Login  => stub("login",  "Run: open https://getship.dev/login"),
            Commands::Logout => run_logout(),
            Commands::Whoami => run_whoami(),
            Commands::Use { mode, path, compile: _ } => run_use(Some(&mode), path),
            Commands::Status { path } => run_status(path),
            Commands::Modes { local, project, cloud } => run_modes(local, project, cloud),
            Commands::Mode { action } => dispatch_mode(action),
            Commands::Compile { provider, dry_run, watch, path } => {
                run_compile_cmd(provider.as_deref(), dry_run, watch, path)
            }
            Commands::Skill { action } => dispatch_skill(action),
            Commands::Mcp { action } => dispatch_mcp(action),
            Commands::Import { source } => {
                stub("import", &format!("Would import from {:?}", source))
            }
            Commands::Export { provider, zip: _ } => {
                run_compile_cmd(Some(&provider), false, false, None)
            }
            Commands::Sync { cmd: _ } => {
                stub("sync", "Cloud sync requires a Ship account. Run: ship login")
            }
            Commands::Server { .. } => {
                stub("server", "Local server (port 7701) — coming soon")
            }
            Commands::Job { action } => dispatch_job(action),
            Commands::Adrs => run_adrs(),
            Commands::Notes => run_notes(),
            Commands::Migrate => run_migrate(),
            Commands::Agent { action } => agent::dispatch_agent(action),
            Commands::Install { frozen } => {
                let root = std::env::current_dir()?;
                install::run_install(&root, frozen)
            }
            Commands::Add { package } => {
                let root = std::env::current_dir()?;
                add::run_add(&root, &package)
            }
            Commands::Profile { action } => dispatch_profile_sync(action),
            Commands::Permissions { action } => dispatch_permissions(action),
            Commands::Next { .. } => stub("next", "Job queue — coming soon"),
            Commands::Retry { .. } => stub("retry", "Job retry — coming soon"),
            Commands::Gate { .. } => stub("gate", "Gate check — coming soon"),
            Commands::Validate { .. } => stub("validate", "Validation — coming soon"),
            Commands::Diff { .. } => stub("diff", "Diff — coming soon"),
            Commands::Matrix { .. } => stub("matrix", "Provider matrix — coming soon"),
        },
    }
}

// ── Init ──────────────────────────────────────────────────────────────────────

fn run_init(global: bool, provider: Option<String>) -> Result<()> {
    if global {
        paths::ensure_global_dirs()?;
        let cfg_path = paths::global_dir().join("config.toml");
        if !cfg_path.exists() {
            std::fs::write(&cfg_path, "# Ship Studio global configuration\n\n[identity]\nname = \"\"\n")?;
        }
        let readme = paths::global_dir().join("README.md");
        if !readme.exists() {
            std::fs::write(&readme, "# Ship\n\nPersonal AI agent configuration. See https://getship.dev\n")?;
        }
        println!("✓ initialized global config at ~/.ship/");
        println!("  Edit ~/.ship/config.toml to set your identity");
    } else {
        paths::ensure_project_dirs()?;
        let ship_toml = paths::project_ship_toml();
        if !ship_toml.exists() {
            let provider_str = provider.as_deref().unwrap_or("claude");
            std::fs::write(&ship_toml, format!(
                "# Ship project configuration\n\n[project]\nproviders = [\"{provider_str}\"]\n"
            ))?;
        }
        let gitignore = paths::project_dir().join(".gitignore");
        if !gitignore.exists() {
            std::fs::write(&gitignore,
                "# Ship — compiled artifacts (regenerated by ship use)\n\
                 /secrets/\nCLAUDE.md\nGEMINI.md\nAGENTS.md\n.mcp.json\n.codex/\n.gemini/\n.cursor/\n"
            )?;
        }
        let readme = paths::project_dir().join("README.md");
        if !readme.exists() {
            std::fs::write(&readme,
                "# Ship Configuration\n\nThis project uses [Ship](https://getship.dev) \
                 to manage AI agent configuration.\n\n\
                 Install the CLI: `curl -fsSL https://getship.dev/install | sh`\n\
                 Then: `ship use <profile-id>` to activate.\n"
            )?;
        }
        println!("✓ initialized .ship/ in current directory");
        println!("  providers: {}", provider.as_deref().unwrap_or("claude"));
        println!("\nNext steps:");
        println!("  ship use <profile-id>   activate a profile (compiles immediately)");
        println!("  ship compile            re-compile current profile");
    }
    Ok(())
}

// ── Auth stubs ────────────────────────────────────────────────────────────────

fn run_logout() -> Result<()> {
    let creds = config::Credentials::load();
    if creds.token().is_none() {
        println!("Not logged in.");
    } else {
        println!("Logged out.");
    }
    Ok(())
}

fn run_whoami() -> Result<()> {
    let cfg = config::ShipConfig::load();
    match cfg.identity {
        Some(id) if !id.name.is_empty() => {
            println!("{}", id.name);
            if let Some(email) = id.email { println!("{}", email); }
        }
        _ => {
            println!("Not logged in.");
            println!("Run: ship init --global");
        }
    }
    Ok(())
}

// ── Use ───────────────────────────────────────────────────────────────────────

/// Activate a profile: load → compile → install plugins → write workspace state to platform.db.
/// `profile_id = None` re-activates the current profile from platform.db.
fn run_use(profile_id: Option<&str>, path: Option<PathBuf>) -> Result<()> {
    let project_root = path.as_deref()
        .map(std::fs::canonicalize)
        .transpose()?
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    if !project_root.join(".ship").exists() {
        anyhow::bail!(".ship/ not found. Run: ship init");
    }

    profile::activate_profile(profile_id, &project_root)
}

// ── Status ────────────────────────────────────────────────────────────────────

fn run_status(path: Option<PathBuf>) -> Result<()> {
    let target = path.as_deref()
        .map(std::fs::canonicalize)
        .transpose()?
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    let ship_dir = target.join(".ship");
    let state = profile::WorkspaceState::load(&ship_dir);
    match state.active_profile {
        Some(ref p) => {
            println!("active profile: {}", p);
            if let Some(ref at) = state.compiled_at { println!("compiled: {}", at); }
            if !state.plugins_installed.is_empty() {
                println!("plugins: {}", state.plugins_installed.join(", "));
            }
        }
        None => {
            println!("No active profile for {}", target.display());
            println!("Run: ship use <profile-id>");
        }
    }
    Ok(())
}

// ── Modes / Profiles ──────────────────────────────────────────────────────────

fn run_modes(local: bool, project: bool, cloud: bool) -> Result<()> {
    if cloud {
        println!("Cloud profiles require a Ship account. Run: ship login");
        return Ok(());
    }
    let modes = paths::list_mode_ids(local, project);
    if modes.is_empty() {
        println!("No profiles found.");
        println!("Create one with: ship mode create <name>");
    } else {
        for (id, scope) in &modes {
            println!("  {} [{}]", id, scope);
        }
    }
    Ok(())
}

// ── Mode subcommands ──────────────────────────────────────────────────────────

fn dispatch_mode(action: ModeCommands) -> Result<()> {
    match action {
        ModeCommands::Create { name, global } => {
            let dir = if global { paths::global_modes_dir() } else { paths::project_presets_dir() };
            std::fs::create_dir_all(&dir)?;
            let path = dir.join(format!("{}.toml", name));
            if path.exists() {
                anyhow::bail!("Profile '{}' already exists at {}", name, path.display());
            }
            std::fs::write(&path, mode::Profile::scaffold(&name))?;
            println!("✓ created profile '{}' at {}", name, path.display());
        }
        ModeCommands::Edit { name, editor } => {
            let path = profile::find_profile_file(&name, &std::env::current_dir()?)
                .ok_or_else(|| anyhow::anyhow!("Profile '{}' not found", name))?;
            let editor = editor.or_else(|| std::env::var("EDITOR").ok()).unwrap_or_else(|| "vi".to_string());
            std::process::Command::new(&editor).arg(&path).status()?;
        }
        ModeCommands::Delete { name } => {
            let path = profile::find_profile_file(&name, &std::env::current_dir()?)
                .ok_or_else(|| anyhow::anyhow!("Profile '{}' not found", name))?;
            std::fs::remove_file(&path)?;
            println!("✓ deleted profile '{}'", name);
        }
        ModeCommands::Clone { source, target } => {
            let cwd = std::env::current_dir()?;
            let src_path = profile::find_profile_file(&source, &cwd)
                .ok_or_else(|| anyhow::anyhow!("Source profile '{}' not found", source))?;
            let dst_path = src_path.parent().unwrap().join(format!("{}.toml", target));
            if dst_path.exists() {
                anyhow::bail!("Target profile '{}' already exists", target);
            }
            let content = std::fs::read_to_string(&src_path)?
                .replace(&format!("id = \"{}\"", source), &format!("id = \"{}\"", target))
                .replace(&format!("name = \"{}\"", source), &format!("name = \"{}\"", target));
            std::fs::write(&dst_path, content)?;
            println!("✓ cloned '{}' → '{}'", source, target);
        }
        ModeCommands::Publish { name: _ } => {
            stub("mode publish", "Publishing requires a Ship account. Run: ship login")?;
        }
    }
    Ok(())
}

// ── Compile ───────────────────────────────────────────────────────────────────

fn run_compile_cmd(provider: Option<&str>, dry_run: bool, watch: bool, path: Option<PathBuf>) -> Result<()> {
    let project_root = path.as_deref()
        .map(std::fs::canonicalize).transpose()?
        .unwrap_or_else(|| std::env::current_dir().unwrap());

    if !project_root.join(".ship").exists() {
        anyhow::bail!(".ship/ not found. Run: ship init");
    }

    let state = profile::WorkspaceState::load(&project_root.join(".ship"));
    compile::run_compile(compile::CompileOptions {
        project_root: &project_root,
        provider,
        dry_run,
        active_mode: state.active_profile.as_deref(),
    })?;

    if watch { println!("--watch not yet implemented. Run compile manually after changes."); }
    Ok(())
}

// ── Job subcommands ───────────────────────────────────────────────────────────

fn dispatch_job(action: JobCommands) -> Result<()> {
    match action {
        JobCommands::Create { kind, title, milestone, description, branch } => {
            job::create(&kind, &title, milestone.as_deref(), description.as_deref(), branch.as_deref())
        }
        JobCommands::List { status, branch, milestone } => {
            job::list(status.as_deref(), branch.as_deref(), milestone.as_deref())
        }
        JobCommands::Update { id, status } => job::update(&id, &status),
        JobCommands::Done { id } => job::update(&id, "complete"),
    }
}

// ── Skill subcommands ─────────────────────────────────────────────────────────

fn dispatch_skill(action: SkillCommands) -> Result<()> {
    match action {
        SkillCommands::List => skill::list(),
        SkillCommands::Create { id, name, description } => skill::create(&id, name.as_deref(), description.as_deref()),
        SkillCommands::Remove { id, global } => skill::remove(&id, global),
        SkillCommands::Add { source, skill, global } => skill::add(&source, skill.as_deref(), global),
        SkillCommands::Update => stub("skill update", "Registry updates — coming soon"),
        SkillCommands::Validate { .. } => stub("skill validate", "Spec validation — coming soon"),
        SkillCommands::Publish { .. } => stub("skill publish", "Publishing requires a Ship account. Run: ship login"),
    }
}

// ── MCP subcommands ───────────────────────────────────────────────────────────

fn dispatch_mcp(action: McpCommands) -> Result<()> {
    match action {
        McpCommands::List => mcp::list(),
        McpCommands::Add { id, name, url, .. } => {
            let url = url.ok_or_else(|| anyhow::anyhow!("--url is required for HTTP/SSE servers"))?;
            mcp::add_http(&id, name, &url)
        }
        McpCommands::AddStdio { id, command, args, name, .. } => mcp::add_stdio(&id, name, &command, args),
        McpCommands::Remove { id } => mcp::remove(&id),
        McpCommands::Probe { id } => stub("mcp probe", &format!("Live probing for {:?} — requires local server", id)),
    }
}

// ── ADRs / Notes ──────────────────────────────────────────────────────────────

fn project_ship_dir() -> Result<std::path::PathBuf> {
    let cwd = std::env::current_dir()?;
    let ship_dir = cwd.join(".ship");
    if !ship_dir.exists() {
        anyhow::bail!(".ship/ not found in {}. Run: ship init", cwd.display());
    }
    Ok(ship_dir)
}

fn run_adrs() -> Result<()> {
    let ship_dir = project_ship_dir()?;
    let adrs = runtime::db::adrs::list_adrs(&ship_dir)?;
    if adrs.is_empty() {
        println!("No ADRs found.");
    } else {
        for entry in &adrs {
            println!("{}\t[{}]\t{}", entry.id, entry.status, entry.title);
        }
    }
    Ok(())
}

fn run_notes() -> Result<()> {
    let ship_dir = project_ship_dir()?;
    let notes = runtime::db::notes::list_notes(&ship_dir, None)?;
    if notes.is_empty() {
        println!("No notes found.");
    } else {
        for entry in &notes {
            println!("{}\t{}", entry.id, entry.title);
        }
    }
    Ok(())
}

fn run_migrate() -> Result<()> {
    let ship_dir = std::env::current_dir()?.join(".ship");
    if !ship_dir.exists() {
        anyhow::bail!(".ship/ not found. Run: ship init");
    }
    let report = runtime::db::migrate_from_state_db::migrate_notes_and_adrs(&ship_dir)?;
    println!("migration complete");
    println!("  notes:  {} migrated, {} skipped", report.notes_migrated, report.notes_skipped);
    println!("  adrs:   {} migrated, {} skipped", report.adrs_migrated, report.adrs_skipped);
    Ok(())
}

// ── Profile sync subcommands ──────────────────────────────────────────────────

fn dispatch_profile_sync(action: ProfileSyncCommands) -> Result<()> {
    match action {
        ProfileSyncCommands::Push => stub("profile push", "Cloud sync requires a Ship account. Run: ship login"),
        ProfileSyncCommands::Pull { .. } => stub("profile pull", "Cloud sync requires a Ship account. Run: ship login"),
    }
}

// ── Permissions subcommands ───────────────────────────────────────────────────

fn dispatch_permissions(action: PermissionsCommands) -> Result<()> {
    match action {
        PermissionsCommands::Sync { path: _ } => stub("permissions sync", "Permission sync — coming soon"),
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn stub(command: &str, note: &str) -> Result<()> {
    println!("[{}] {}", command, note);
    Ok(())
}
