use anyhow::{Result, bail};
use std::fmt::Write as FmtWrite;

// CORE_TOOLS kept in sync with apps/mcp/src/server.rs::core_tools().
// If you update one, update the other.
const CORE_TOOLS: &[&str] = &[
    "open_project",
    "create_note",
    "update_note",
    "create_adr",
    "activate_workspace",
    "create_workspace",
    "complete_workspace",
    "list_stale_worktrees",
    "set_agent",
    "list_workspaces",
    "start_session",
    "end_session",
    "log_progress",
    "list_skills",
    "create_job",
    "update_job",
    "list_jobs",
    "append_job_log",
    "claim_file",
    "get_file_owner",
    "list_events",
    "provider_matrix",
];

pub fn generate() -> String {
    let mut out = String::new();
    writeln!(out, "# Ship Surface").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "Generated by `ship surface`. Do not edit manually.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "## CLI Commands").unwrap();
    writeln!(out).unwrap();
    write_cli_tree(&mut out);
    writeln!(out).unwrap();
    writeln!(out, "## MCP Core Tools").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "Tools always available regardless of active agent:").unwrap();
    writeln!(out).unwrap();
    let mut tools: Vec<&str> = CORE_TOOLS.to_vec();
    tools.sort_unstable();
    for tool in tools {
        writeln!(out, "- `{}`", tool).unwrap();
    }
    out
}

fn write_cli_tree(out: &mut String) {
    let entries: &[(&str, &str, Option<&[(&str, &str)]>)] = &[
        ("ship init", "Scaffold .ship/ in the current project, or configure ~/.ship/ globally", Some(&[
            ("--global", "Configure ~/.ship/ instead of current project"),
            ("--provider <id>", "Default provider (claude, gemini, codex, cursor)"),
            ("--force", "Overwrite existing .ship/"),
        ])),
        ("ship login", "Authenticate with getship.dev", None),
        ("ship logout", "Sign out", None),
        ("ship whoami", "Show current identity", None),
        ("ship use <agent-id>", "Activate an agent (compiles immediately)", Some(&[
            ("--path <dir>", "Bind to this path instead of cwd"),
        ])),
        ("ship status", "Show active agent and compilation status", Some(&[
            ("--path <dir>", "Target directory"),
        ])),
        ("ship compile", "Compile the active agent to provider-native config files", Some(&[
            ("--provider <id>", "Compile for a specific provider only"),
            ("--dry-run", "Preview without writing files"),
            ("--watch", "Recompile on changes (not yet implemented)"),
            ("--path <dir>", "Project root"),
        ])),
        ("ship agent", "Manage agents", Some(&[
            ("list [--local] [--project]", "List available agents"),
            ("create <name> [--global]", "Create a new agent"),
            ("edit <name>", "Open agent in $EDITOR"),
            ("delete <name>", "Delete an agent"),
            ("clone <source> <target>", "Clone an agent under a new ID"),
        ])),
        ("ship skill", "Manage agent skills", Some(&[
            ("add <source> [--skill <id>] [--global]", "Install a skill"),
            ("list", "List installed skills"),
            ("remove <id> [--global]", "Remove a skill"),
            ("create <id>", "Scaffold a new skill"),
        ])),
        ("ship mcp", "Manage MCP servers", Some(&[
            ("serve [--http] [--port <n>]", "Run the Ship MCP server"),
            ("add <id> --url <url>", "Register an HTTP/SSE server"),
            ("add-stdio <id> <command> [args...]", "Register a stdio server"),
            ("list", "List configured servers"),
            ("remove <id>", "Remove a server"),
        ])),
        ("ship install", "Install all dependencies in .ship/ship.toml", Some(&[
            ("--frozen", "Fail if lockfile would change"),
        ])),
        ("ship add <package>", "Add a dependency to .ship/ship.toml and install it", None),
        ("ship import <source>", "Import an agent from a URL, path, or provider config", None),
        ("ship validate", "Validate .ship/ config before compile", Some(&[
            ("--agent <id>", "Validate a single agent"),
            ("--json", "Emit errors as JSON"),
            ("--path <dir>", "Project root"),
        ])),
        ("ship events list", "Query the project event log", Some(&[
            ("--since <time>", "Since timestamp or relative (e.g. 1h, 24h)"),
            ("--actor <name>", "Filter by actor"),
            ("--entity <type>", "Filter by entity type"),
            ("--action <name>", "Filter by action"),
            ("--limit <n>", "Max events (default 50)"),
            ("--json", "Output as JSON"),
        ])),
        ("ship surface", "Print CLI + MCP surface as markdown", Some(&[
            ("--emit", "Write output to docs/surface.md"),
            ("--check", "Diff against docs/surface.md; exit 1 if drift detected"),
        ])),
    ];

    for (cmd, desc, flags) in entries {
        writeln!(out, "### `{}`", cmd).unwrap();
        writeln!(out).unwrap();
        writeln!(out, "{}", desc).unwrap();
        if let Some(flags) = flags {
            writeln!(out).unwrap();
            for (flag, fdesc) in *flags {
                writeln!(out, "- `{}` — {}", flag, fdesc).unwrap();
            }
        }
        writeln!(out).unwrap();
    }
}

pub fn run(emit: bool, check: bool) -> Result<()> {
    let output = generate();

    if emit {
        let docs_dir = std::env::current_dir()?.join("docs");
        std::fs::create_dir_all(&docs_dir)?;
        let path = docs_dir.join("surface.md");
        std::fs::write(&path, &output)?;
        println!("wrote {}", path.display());
    } else if check {
        let path = std::env::current_dir()?.join("docs").join("surface.md");
        if !path.exists() {
            bail!("docs/surface.md not found. Run: ship surface --emit");
        }
        let committed = std::fs::read_to_string(&path)?;
        if committed != output {
            eprintln!("surface drift detected: docs/surface.md is out of date.");
            eprintln!("Run: ship surface --emit   then commit docs/surface.md");
            std::process::exit(1);
        }
        println!("surface OK: docs/surface.md matches current CLI + MCP surface");
    } else {
        print!("{}", output);
    }

    Ok(())
}
