// This file is auto-generated by `cargo xtask gen-types`. Do not edit.


/**
 * Agent configuration within a transfer bundle.
 */
export type AgentBundle = { id: string; name?: string | null; description?: string | null; model?: string | null; skills?: string[]; rules?: string[]; mcp_servers?: JsonValue[] }

export type AgentLayerConfig = { skills?: string[]; prompts?: string[]; context?: string[] }

export type AgentLimits = { max_cost_per_session?: number | null; max_turns?: number | null; require_confirmation?: string[] }

/**
 * An agent parsed from `.ship/agents/<id>.toml`.
 * 
 * Profiles define specialist agents that the compiler emits as
 * provider-native subagent definitions (`.claude/agents/`, `.gemini/agents/`,
 * `.cursor/agents/`, `.codex/agents/`).
 */
export type AgentProfile = { profile: ProfileMeta; skills?: SkillRefs; mcp?: McpRefs; plugins?: PluginRefs; permissions?: ProfilePermissions; rules?: ProfileRules }

export type AiConfig = { provider: string | null; model: string | null; cli_path: string | null }

/**
 * Grouping category for catalog browsing.
 */
export type CatalogCategory = "database" | "communication" | "development" | "search" | "automation" | "ai" | "storage" | "monitoring" | "cloud"

/**
 * A browsable catalog entry with rich metadata for UI display.
 * 
 * Curated by Ship. Every entry is vetted for security, stability, and usefulness.
 * The embedded list is the baseline. The web product will supplement this
 * via API (agentskills.io, mcp.so, or the Ship-hosted registry).
 */
export type CatalogEntry = { id: string; name: string; description: string; kind: CatalogKind; category: CatalogCategory; tags: string[]; 
/**
 * Emoji icon for UI display.
 */
icon: string; 
/**
 * Whether this is an official first-party entry (MCP org or vendor-maintained).
 */
official: boolean; author: string | null; 
/**
 * SPDX license identifier.
 */
license: string | null; source_url: string | null; install_command: string | null; command: string | null; args: string[]; 
/**
 * Environment variables the server requires.
 */
env_vars: string[]; 
/**
 * For skills: the prompt template body.
 */
skill_template: string | null }

export type CatalogKind = "skill" | "mcp-server"

export type CommandPermissions = { allow?: string[]; deny?: string[] }

/**
 * The content generated by the compiler for a given provider.
 * All values are strings ready to write; no filesystem access required.
 */
export type CompileOutput = { 
/**
 * MCP server entries to inject into the target config file.
 * Key = provider's `mcp_key` value, value = JSON object mapping server ID → entry.
 */
mcp_servers: JsonValue; 
/**
 * Project-relative path where the MCP config file should be written,
 * e.g. `".mcp.json"` for Claude or `".cursor/mcp.json"` for Cursor.
 * `None` when the provider merges MCP into a larger settings file.
 */
mcp_config_path: string | null; 
/**
 * Context file content (CLAUDE.md / GEMINI.md / AGENTS.md).
 * `None` if the provider has no context file or there is no content to emit.
 */
context_content: string | null; 
/**
 * Skill files: path relative to project root → file content.
 * e.g. `".claude/skills/my-skill/SKILL.md" → "---\nname: my-skill\n..."`.
 */
skill_files: Partial<{ [key in string]: string }>; 
/**
 * Claude settings patch: `permissions`, `hooks`, agent limits.
 * Only populated for the `claude` provider.
 */
claude_settings_patch: JsonValue | null; 
/**
 * Codex config patch: `[mcp_servers.<id>]` TOML tables.
 * Only populated for the `codex` provider.
 * Merge into `.codex/config.toml`.
 */
codex_config_patch: string | null; 
/**
 * Gemini settings patch: `hooks` section for `.gemini/settings.json`.
 * Only populated for the `gemini` provider when hooks are present.
 * Merge alongside `mcpServers` in `.gemini/settings.json`.
 */
gemini_settings_patch: JsonValue | null; 
/**
 * Gemini policy file content for `.gemini/policies/ship.toml`.
 * Only populated for the `gemini` provider when permissions are non-default.
 * Decisions: `allow`, `deny`, `ask_user`. Tool names: `shell`, `mcp`,
 * `file_read`, `file_write`, `web_fetch`.
 */
gemini_policy_patch: string | null; 
/**
 * Cursor hooks file: full `.cursor/hooks.json` content.
 * Only populated for the `cursor` provider when hooks are present.
 */
cursor_hooks_patch: JsonValue | null; 
/**
 * Cursor permissions: `{ "version": 1, "permissions": { "allow": [...], "deny": [...] } }`
 * Written to `.cursor/cli.json` (project) or `~/.cursor/cli-config.json` (global).
 * Applies to both Cursor IDE agents and the Cursor CLI.
 * Only populated when permissions are non-default. Never emits a permissive allow-all
 * unless the user explicitly supplies the typed wildcard patterns.
 */
cursor_cli_permissions: JsonValue | null; 
/**
 * Per-file rule output for providers that use individual rule files.
 * Key = relative path (e.g. `.cursor/rules/style.mdc`), value = file content.
 * Populated for Cursor (per-file .mdc). Other providers use `context_content`.
 */
rule_files: Partial<{ [key in string]: string }>; 
/**
 * Plugin install intent declared by the active preset.
 * This is a pure output artifact — the compiler never installs plugins.
 * The CLI/runtime reads this after compilation and executes the lifecycle.
 */
plugins_manifest: PluginsManifest; 
/**
 * Provider-native agent definition files.
 * Key = path relative to project root (e.g. `.claude/agents/monitor.md`).
 * Value = file content. Written verbatim by the CLI.
 */
agent_files: Partial<{ [key in string]: string }>; 
/**
 * Cursor-only: `.cursor/environment.json` content.
 * Only populated when `cursor_environment` is set in the resolved config.
 */
cursor_environment_json: JsonValue | null; 
/**
 * OpenCode-only: full `opencode.json` content (model + MCP + extras).
 * Only populated for the `opencode` provider.
 */
opencode_config_patch: JsonValue | null }

export type FsPermissions = { allow?: string[]; deny?: string[] }

export type GitConfig = { ignore?: string[]; commit?: string[] }

export type HookConfig = { id: string; trigger: HookTrigger; matcher?: string | null; command: string; 
/**
 * Raw Cursor event name; when set, bypasses trigger mapping and emits directly.
 */
cursor_event?: string | null; 
/**
 * Raw Gemini event name; when set, bypasses trigger mapping and emits directly.
 */
gemini_event?: string | null }

export type HookTrigger = "PreToolUse" | "PostToolUse" | "Notification" | "Stop" | "SubagentStop" | "PreCompact"

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/**
 * Response from list_local_agents MCP tool.
 */
export type ListAgentsResponse = { agents: string[] }

export type McpRefs = { servers?: string[] }

export type McpServerConfig = { id?: string; name: string; command: string; args?: string[]; env?: Partial<{ [key in string]: string }>; scope?: string; server_type?: McpServerType; url: string | null; disabled?: boolean; timeout_secs: number | null; 
/**
 * Codex: tool names to enable for this server.
 */
codex_enabled_tools: string[]; 
/**
 * Codex: tool names to disable for this server.
 */
codex_disabled_tools: string[]; 
/**
 * Gemini: whether this server is trusted.
 */
gemini_trust?: boolean | null; 
/**
 * Gemini: tool names to include from this server.
 */
gemini_include_tools: string[]; 
/**
 * Gemini: tool names to exclude from this server.
 */
gemini_exclude_tools: string[]; 
/**
 * Gemini: per-server timeout in milliseconds.
 */
gemini_timeout_ms?: number | null; 
/**
 * Cursor: path to an env file to load for this stdio server.
 */
cursor_env_file?: string | null }

export type McpServerType = "stdio" | "sse" | "http"

export type ModeConfig = { id: string; name: string; description?: string | null; active_tools?: string[]; mcp_servers?: string[]; skills?: string[]; rules?: string[]; prompt_id?: string | null; hooks?: HookConfig[]; permissions?: PermissionConfig; target_agents?: string[] }

export type NamespaceConfig = { id: string; path: string; owner: string }

export type NetworkPermissions = { policy?: NetworkPolicy; allow_hosts?: string[] }

export type NetworkPolicy = "none" | "localhost" | "allow-list" | "unrestricted"

export type PermissionConfig = { allow?: string[]; deny?: string[] }

export type Permissions = { tools?: ToolPermissions; filesystem?: FsPermissions; commands?: CommandPermissions; network?: NetworkPermissions; agent?: AgentLimits; 
/**
 * Claude Code default permission mode: "default", "acceptEdits", "plan", "bypassPermissions".
 */
default_mode?: string | null; 
/**
 * Additional working directories Claude has access to.
 */
additional_directories?: string[] }

/**
 * A single plugin to install.
 */
export type PluginEntry = { 
/**
 * Plugin ID, e.g. `"superpowers@claude-plugins-official"`.
 */
id: string; 
/**
 * Provider this plugin belongs to, e.g. `"claude"`.
 */
provider: string }

export type PluginRefs = { install?: string[]; scope?: string | null }

/**
 * Declared plugin intent produced by the compiler.
 * The CLI/runtime reads this and executes installs — the compiler never does.
 */
export type PluginsManifest = { 
/**
 * Plugins that should be installed.
 */
install: PluginEntry[]; 
/**
 * Installation scope: `"project"` | `"user"`.
 */
scope: string }

export type ProfileMeta = { id: string; name: string; version?: string | null; description?: string | null; providers?: string[] }

export type ProfilePermissions = { 
/**
 * Permission preset name (e.g. "ship-standard", "ship-autonomous").
 */
preset?: string | null; tools_allow?: string[]; tools_ask?: string[]; tools_deny?: string[]; 
/**
 * Claude Code permission mode: "default", "acceptEdits", "plan", "bypassPermissions".
 */
default_mode?: string | null }

export type ProfileRules = { 
/**
 * Inline rules body — becomes the agent's system prompt.
 */
inline?: string | null }

export type ProjectConfig = { version?: string; id?: string; name: string | null; description: string | null; statuses?: StatusConfig[]; providers?: string[]; ai: AiConfig | null; modes?: ModeConfig[]; active_agent?: string | null; mcp_servers?: McpServerConfig[]; hooks?: HookConfig[]; namespaces?: NamespaceConfig[]; git?: GitConfig }

/**
 * Resolve the effective agent config from pre-loaded project data.
 * 
 * Resolution order (highest wins):
 * 1. Project defaults (manifest types + `agents/` content)
 * 2. Active mode filter (restricts servers/skills/rules)
 * 3. Feature overrides (model, providers, additional server/skill filter)
 * 
 * A self-contained library of agent config assets loaded from the `agents/`
 * directory. This is the primary input for the compiler in the new config model:
 * The manifest holds identity only; the library holds everything the compiler needs.
 */
export type ProjectLibrary = { 
/**
 * Agent definitions from `agents/*.jsonc`.
 */
modes?: ModeConfig[]; 
/**
 * Active agent for this resolve (e.g. workspace override).
 */
active_agent?: string | null; 
/**
 * MCP server definitions from `mcp.jsonc`.
 */
mcp_servers?: McpServerConfig[]; 
/**
 * Skills from `skills/`.
 */
skills?: Skill[]; 
/**
 * Rules from `rules/`.
 */
rules?: Rule[]; 
/**
 * Permissions from `agents/permissions.toml`.
 */
permissions?: Permissions; 
/**
 * Hooks from `agents/hooks.toml`.
 */
hooks?: HookConfig[]; 
/**
 * Plugin install intent from the active preset's `[plugins]` section.
 */
plugins?: PluginsManifest; 
/**
 * Project-level provider defaults from `project.provider_defaults` in `ship.jsonc`.
 * Merged as base under agent-level `*_settings_extra` during resolution.
 */
provider_defaults: Partial<{ [key in string]: JsonValue }>; 
/**
 * Pass-through from `[provider_settings.claude]` in the active preset.
 * Merged verbatim into `.claude/settings.json` on compile.
 */
claude_settings_extra?: JsonValue | null; 
/**
 * Agent profiles from `.ship/agents/*.toml`.
 */
agent_profiles: AgentProfile[]; 
/**
 * Team agent files: `.ship/agents/teams/claude/<name>.md` → `.claude/agents/<name>.md`.
 */
claude_team_agents: ([string, string])[]; 
/**
 * Environment variables: KEY=VALUE pairs injected into provider settings.
 */
env: Partial<{ [key in string]: string }>; 
/**
 * Restrict model picker to these IDs.
 */
available_models: string[]; 
/**
 * Codex sandbox mode — translated key/value before emit.
 */
codex_sandbox?: string | null; 
/**
 * Shared model override used by Gemini + Codex when no feature override present.
 */
model?: string | null; gemini_default_approval_mode?: string | null; gemini_max_session_turns?: number | null; gemini_disable_yolo_mode?: boolean | null; gemini_disable_always_allow?: boolean | null; gemini_tools_sandbox?: string | null; gemini_settings_extra?: JsonValue | null; codex_approval_policy?: string | null; codex_reasoning_effort?: string | null; codex_max_threads?: number | null; codex_max_depth?: number | null; codex_job_max_runtime_seconds?: number | null; codex_shell_env_policy?: string | null; codex_notify?: JsonValue | null; codex_settings_extra?: JsonValue | null; opencode_settings_extra?: JsonValue | null; cursor_environment?: JsonValue | null; cursor_settings_extra?: JsonValue | null; claude_theme?: string | null; claude_auto_updates?: boolean | null; claude_include_co_authored_by?: boolean | null }

/**
 * Resolved agent as returned by pull_agents.
 */
export type PullAgent = { profile: PullProfile; skills: PullSkill[]; mcpServers: PullMcpServer[]; rules: PullRule[]; hooks: JsonValue[]; permissions?: JsonValue | null; 
/**
 * "project" (from .ship/) or "library" (from ~/.ship/).
 */
source?: string }

/**
 * MCP server reference as returned by pull_agents.
 */
export type PullMcpServer = { name: string; command: string; url?: string | null }

/**
 * Agent profile metadata as returned by pull_agents.
 */
export type PullProfile = { id: string; name: string; description: string; providers: string[]; version: string }

/**
 * Response from pull_agents MCP tool.
 */
export type PullResponse = { agents: PullAgent[] }

/**
 * Rule with content as returned by pull_agents.
 */
export type PullRule = { file_name: string; content: string }

/**
 * Skill with content as returned by pull_agents.
 */
export type PullSkill = { id: string; name: string; description?: string | null; content: string; source: string }

/**
 * A rule from `agents/rules/*.md`. Always active — no mode/feature filtering.
 * The compiler receives pre-loaded `Rule` values — it does not read files.
 */
export type Rule = { file_name: string; content: string; 
/**
 * If true, inject into every agent context (default). False = conditional.
 */
always_apply?: boolean; 
/**
 * File glob patterns — Cursor "Apply to Specific Files" mode.
 */
globs?: string[]; 
/**
 * Description for "Apply Intelligently" mode (Cursor).
 */
description?: string | null }

/**
 * A skill / slash command. Stored as `agents/skills/<id>/SKILL.md` (agentskills.io spec).
 * The compiler receives pre-loaded `Skill` values — it does not read files.
 */
export type Skill = { id: string; name: string; description?: string | null; license?: string | null; compatibility?: string | null; 
/**
 * Parsed from the space-delimited `allowed-tools` frontmatter key.
 */
allowed_tools?: string[]; 
/**
 * Arbitrary key-value metadata from the `metadata` frontmatter block.
 */
metadata?: Partial<{ [key in string]: string }>; content: string; source?: SkillSource }

/**
 * Skill files within a transfer bundle.
 */
export type SkillBundle = { files: Partial<{ [key in string]: string }> }

export type SkillRefs = { refs?: string[] }

export type SkillSource = "custom" | "builtin" | "ai-generated" | "community" | "imported"

export type StatusConfig = { id: string; name: string; color?: string }

export type ToolPermissions = { allow?: string[]; 
/**
 * Patterns that trigger confirmation before tool use (Claude "ask" tier).
 */
ask?: string[]; deny?: string[] }

/**
 * Bundle sent from Studio to the local CLI via MCP push_bundle tool.
 */
export type TransferBundle = { agent: AgentBundle; dependencies?: Partial<{ [key in string]: string }>; skills?: Partial<{ [key in string]: SkillBundle }> }

