use serde::{Deserialize, Serialize};

/// Grouping category for catalog browsing.
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum CatalogCategory {
    Database,
    Communication,
    Development,
    Search,
    Automation,
    Ai,
    Storage,
    Monitoring,
    Cloud,
}

#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum CatalogKind {
    Skill,
    McpServer,
}

/// A browsable catalog entry with rich metadata for UI display.
///
/// Curated by Ship. Every entry is vetted for security, stability, and usefulness.
/// The embedded list is the baseline. The web product will supplement this
/// via API (agentskills.io, mcp.so, or the Ship-hosted registry).
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct CatalogEntry {
    pub id: String,
    pub name: String,
    pub description: String,
    pub kind: CatalogKind,
    pub category: CatalogCategory,
    pub tags: Vec<String>,
    /// Emoji icon for UI display.
    pub icon: String,
    /// Whether this is an official first-party entry (MCP org or vendor-maintained).
    pub official: bool,
    pub author: Option<String>,
    /// SPDX license identifier.
    pub license: Option<String>,
    pub source_url: Option<String>,
    pub install_command: Option<String>,
    pub command: Option<String>,
    pub args: Vec<String>,
    /// Environment variables the server requires.
    pub env_vars: Vec<String>,
    /// For skills: the prompt template body.
    pub skill_template: Option<String>,
}

// ─── Embedded catalog ─────────────────────────────────────────────────────────

struct StaticEntry {
    id: &'static str,
    name: &'static str,
    description: &'static str,
    kind: CatalogKind,
    category: CatalogCategory,
    tags: &'static [&'static str],
    icon: &'static str,
    official: bool,
    author: Option<&'static str>,
    license: Option<&'static str>,
    source_url: Option<&'static str>,
    install_command: Option<&'static str>,
    command: Option<&'static str>,
    args: &'static [&'static str],
    env_vars: &'static [&'static str],
    skill_template: Option<&'static str>,
}

fn to_entry(s: &StaticEntry) -> CatalogEntry {
    CatalogEntry {
        id: s.id.to_string(),
        name: s.name.to_string(),
        description: s.description.to_string(),
        kind: s.kind.clone(),
        category: s.category.clone(),
        tags: s.tags.iter().map(|t| t.to_string()).collect(),
        icon: s.icon.to_string(),
        official: s.official,
        author: s.author.map(|a| a.to_string()),
        license: s.license.map(|l| l.to_string()),
        source_url: s.source_url.map(|u| u.to_string()),
        install_command: s.install_command.map(|c| c.to_string()),
        command: s.command.map(|c| c.to_string()),
        args: s.args.iter().map(|a| a.to_string()).collect(),
        env_vars: s.env_vars.iter().map(|e| e.to_string()).collect(),
        skill_template: s.skill_template.map(|t| t.to_string()),
    }
}

static EMBEDDED: &[StaticEntry] = &[
    // ── Skills ────────────────────────────────────────────────────────────────
    StaticEntry {
        id: "code-review",
        name: "Code Review",
        description: "Review code for correctness, security, performance, and style.",
        kind: CatalogKind::Skill,
        category: CatalogCategory::Development,
        tags: &["review", "quality", "security"],
        icon: "check-circle",
        official: false,
        author: Some("community"),
        license: None,
        source_url: Some("https://agentskills.io"),
        install_command: None,
        command: None,
        args: &[],
        env_vars: &[],
        skill_template: Some(
            "Review the following code for correctness, security, performance, and style.\n\
             Return feedback as a markdown list grouped by severity (critical / major / minor).\n\n\
             Code to review:\n$ARGUMENTS",
        ),
    },
    StaticEntry {
        id: "test-generator",
        name: "Test Generator",
        description: "Generate unit tests for a function or module. Multi-framework.",
        kind: CatalogKind::Skill,
        category: CatalogCategory::Development,
        tags: &["testing", "quality", "automation"],
        icon: "flask",
        official: false,
        author: Some("community"),
        license: None,
        source_url: Some("https://agentskills.io"),
        install_command: None,
        command: None,
        args: &[],
        env_vars: &[],
        skill_template: Some(
            "Generate comprehensive unit tests for the following code.\n\
             Use the project's existing test framework and conventions.\n\
             Include happy path, edge cases, and error cases.\n\n\
             Code to test:\n$ARGUMENTS",
        ),
    },
    StaticEntry {
        id: "commit-message",
        name: "Commit Message",
        description: "Generate a conventional commit message from a diff or description.",
        kind: CatalogKind::Skill,
        category: CatalogCategory::Development,
        tags: &["git", "workflow", "conventions"],
        icon: "git-commit",
        official: false,
        author: Some("community"),
        license: None,
        source_url: Some("https://agentskills.io"),
        install_command: None,
        command: None,
        args: &[],
        env_vars: &[],
        skill_template: Some(
            "Generate a conventional commit message for the following changes.\n\
             Format: <type>(<scope>): <description>\n\
             Types: feat, fix, docs, refactor, test, chore, perf, ci\n\
             Keep the subject line under 72 characters. Add a body if needed.\n\n\
             Changes:\n$ARGUMENTS",
        ),
    },
    StaticEntry {
        id: "debug-assistant",
        name: "Debug Assistant",
        description: "Systematic debugging: hypothesis, reproduction, fix, verification.",
        kind: CatalogKind::Skill,
        category: CatalogCategory::Development,
        tags: &["debugging", "troubleshooting"],
        icon: "bug",
        official: false,
        author: Some("community"),
        license: None,
        source_url: Some("https://agentskills.io"),
        install_command: None,
        command: None,
        args: &[],
        env_vars: &[],
        skill_template: Some(
            "Debug the following issue step by step:\n\
             1. State your hypothesis about the root cause\n\
             2. Identify the smallest reproduction case\n\
             3. Propose a fix with rationale\n\
             4. Describe how to verify the fix\n\n\
             Issue:\n$ARGUMENTS",
        ),
    },
    StaticEntry {
        id: "doc-writer",
        name: "Documentation Writer",
        description: "Generate clear documentation for a function, module, or API.",
        kind: CatalogKind::Skill,
        category: CatalogCategory::Development,
        tags: &["docs", "documentation", "api"],
        icon: "file-text",
        official: false,
        author: Some("community"),
        license: None,
        source_url: Some("https://agentskills.io"),
        install_command: None,
        command: None,
        args: &[],
        env_vars: &[],
        skill_template: Some(
            "Write comprehensive documentation for the following code.\n\
             Include: purpose, parameters, return values, errors, and usage examples.\n\
             Match the project's existing doc style.\n\n\
             Code:\n$ARGUMENTS",
        ),
    },
    StaticEntry {
        id: "refactor-plan",
        name: "Refactor Planner",
        description: "Step-by-step refactoring plan with risk assessment and rollback notes.",
        kind: CatalogKind::Skill,
        category: CatalogCategory::Development,
        tags: &["refactoring", "architecture", "planning"],
        icon: "layers",
        official: false,
        author: Some("community"),
        license: None,
        source_url: Some("https://agentskills.io"),
        install_command: None,
        command: None,
        args: &[],
        env_vars: &[],
        skill_template: Some(
            "Create a refactoring plan for the following code or system.\n\
             Include:\n\
             - Goal and motivation\n\
             - Step-by-step changes (each independently deployable)\n\
             - Risk assessment per step\n\
             - Rollback strategy\n\n\
             Target:\n$ARGUMENTS",
        ),
    },
    // ── Official MCP servers (modelcontextprotocol/servers) ──────────────────
    StaticEntry {
        id: "mcp-filesystem",
        name: "Filesystem",
        description: "Read, write, and search files with configurable allowed paths.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Storage,
        tags: &["filesystem", "files", "local"],
        icon: "folder",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some(
            "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
        ),
        install_command: Some("npx -y @modelcontextprotocol/server-filesystem"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-filesystem", "{path}"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-github",
        name: "GitHub",
        description: "Repos, issues, pull requests, and actions via the GitHub API.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Development,
        tags: &["github", "git", "vcs", "issues", "prs"],
        icon: "git-branch",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/github"),
        install_command: Some("npx -y @modelcontextprotocol/server-github"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-github"],
        env_vars: &["GITHUB_TOKEN"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-git",
        name: "Git",
        description: "Read and search local Git repos. Diffs, logs, branches, blame.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Development,
        tags: &["git", "vcs", "local", "diff"],
        icon: "git-commit",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/git"),
        install_command: Some("npx -y @modelcontextprotocol/server-git"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-git", "--repository", "{path}"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-postgres",
        name: "PostgreSQL",
        description: "Query and inspect a PostgreSQL database. Read-only by default.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Database,
        tags: &["database", "postgres", "sql"],
        icon: "database",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/postgres"),
        install_command: Some("npx -y @modelcontextprotocol/server-postgres"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-postgres", "{connection_string}"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-sqlite",
        name: "SQLite",
        description: "Query and inspect a local SQLite database file.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Database,
        tags: &["database", "sqlite", "sql", "local"],
        icon: "database",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite"),
        install_command: Some("npx -y @modelcontextprotocol/server-sqlite"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-sqlite", "--db-path", "{db_path}"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-fetch",
        name: "Fetch",
        description: "Fetch URLs and convert HTML to markdown. Robots.txt aware.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Search,
        tags: &["web", "http", "fetch", "scrape"],
        icon: "globe",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/fetch"),
        install_command: Some("npx -y @modelcontextprotocol/server-fetch"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-fetch"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-memory",
        name: "Memory",
        description: "Knowledge graph-based persistent memory across sessions.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Ai,
        tags: &["memory", "context", "persistence", "knowledge-graph"],
        icon: "brain",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/memory"),
        install_command: Some("npx -y @modelcontextprotocol/server-memory"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-memory"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-brave-search",
        name: "Brave Search",
        description: "Web and local search via the Brave Search API.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Search,
        tags: &["search", "web", "brave"],
        icon: "search",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some(
            "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
        ),
        install_command: Some("npx -y @modelcontextprotocol/server-brave-search"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-brave-search"],
        env_vars: &["BRAVE_API_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-puppeteer",
        name: "Puppeteer",
        description: "Browser automation via Puppeteer. Navigate, screenshot, interact.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Automation,
        tags: &["browser", "automation", "scraping", "testing"],
        icon: "monitor",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some(
            "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
        ),
        install_command: Some("npx -y @modelcontextprotocol/server-puppeteer"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-puppeteer"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-slack",
        name: "Slack",
        description: "Read channels, post messages, and list users in a Slack workspace.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Communication,
        tags: &["slack", "messaging", "team"],
        icon: "message-square",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some("https://github.com/modelcontextprotocol/servers/tree/main/src/slack"),
        install_command: Some("npx -y @modelcontextprotocol/server-slack"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-slack"],
        env_vars: &["SLACK_BOT_TOKEN", "SLACK_TEAM_ID"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-sequential-thinking",
        name: "Sequential Thinking",
        description: "Structured multi-step reasoning. Improves complex problem solving.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Ai,
        tags: &["reasoning", "thinking", "chain-of-thought"],
        icon: "lightbulb",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some(
            "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
        ),
        install_command: Some("npx -y @modelcontextprotocol/server-sequential-thinking"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-sequential-thinking"],
        env_vars: &[],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-google-maps",
        name: "Google Maps",
        description: "Geocoding, directions, places, and elevation via Google Maps API.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Search,
        tags: &["maps", "geocoding", "directions", "places"],
        icon: "map-pin",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some(
            "https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps",
        ),
        install_command: Some("npx -y @modelcontextprotocol/server-google-maps"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-google-maps"],
        env_vars: &["GOOGLE_MAPS_API_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-everything",
        name: "Everything",
        description: "Reference MCP server exercising all protocol features. For testing.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Development,
        tags: &["testing", "reference", "debug"],
        icon: "wrench",
        official: true,
        author: Some("Anthropic"),
        license: Some("MIT"),
        source_url: Some(
            "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
        ),
        install_command: Some("npx -y @modelcontextprotocol/server-everything"),
        command: Some("npx"),
        args: &["-y", "@modelcontextprotocol/server-everything"],
        env_vars: &[],
        skill_template: None,
    },
    // ── First-party vendor MCP servers ──────────────────────────────────────
    StaticEntry {
        id: "mcp-sentry",
        name: "Sentry",
        description: "Search issues, view stack traces, and query error data from Sentry.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Monitoring,
        tags: &["sentry", "errors", "monitoring", "debugging"],
        icon: "alert-triangle",
        official: true,
        author: Some("Sentry"),
        license: Some("Apache-2.0"),
        source_url: Some("https://github.com/getsentry/sentry-mcp"),
        install_command: Some("npx -y @sentry/mcp-server"),
        command: Some("npx"),
        args: &["-y", "@sentry/mcp-server"],
        env_vars: &["SENTRY_AUTH_TOKEN"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-linear",
        name: "Linear",
        description: "Issues, projects, and cycles from Linear. Create, update, search.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Development,
        tags: &["linear", "issues", "project-management"],
        icon: "list-checks",
        official: true,
        author: Some("Linear"),
        license: Some("MIT"),
        source_url: Some("https://github.com/linear/linear-mcp-server"),
        install_command: Some("npx -y @linear/mcp-server"),
        command: Some("npx"),
        args: &["-y", "@linear/mcp-server"],
        env_vars: &["LINEAR_API_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-notion",
        name: "Notion",
        description: "Search, read, and create pages and databases in Notion.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Communication,
        tags: &["notion", "wiki", "documents", "knowledge-base"],
        icon: "file-text",
        official: true,
        author: Some("Notion"),
        license: Some("MIT"),
        source_url: Some("https://github.com/notionhq/notion-mcp-server"),
        install_command: Some("npx -y @notionhq/notion-mcp-server"),
        command: Some("npx"),
        args: &["-y", "@notionhq/notion-mcp-server"],
        env_vars: &["NOTION_API_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-stripe",
        name: "Stripe",
        description: "Payments, customers, subscriptions, and invoices via Stripe API.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Cloud,
        tags: &["stripe", "payments", "billing", "commerce"],
        icon: "credit-card",
        official: true,
        author: Some("Stripe"),
        license: Some("MIT"),
        source_url: Some("https://github.com/stripe/agent-toolkit"),
        install_command: Some("npx -y @stripe/mcp"),
        command: Some("npx"),
        args: &["-y", "@stripe/mcp"],
        env_vars: &["STRIPE_SECRET_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-cloudflare",
        name: "Cloudflare",
        description: "Workers, KV, R2, D1, and DNS management via Cloudflare API.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Cloud,
        tags: &["cloudflare", "workers", "cdn", "dns", "edge"],
        icon: "cloud",
        official: true,
        author: Some("Cloudflare"),
        license: Some("Apache-2.0"),
        source_url: Some("https://github.com/cloudflare/mcp-server-cloudflare"),
        install_command: Some("npx -y @cloudflare/mcp-server-cloudflare"),
        command: Some("npx"),
        args: &["-y", "@cloudflare/mcp-server-cloudflare"],
        env_vars: &["CLOUDFLARE_API_TOKEN"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-vercel",
        name: "Vercel",
        description: "Deployments, projects, domains, and env vars on Vercel.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Cloud,
        tags: &["vercel", "deployments", "hosting", "next-js"],
        icon: "rocket",
        official: true,
        author: Some("Vercel"),
        license: Some("MIT"),
        source_url: Some("https://github.com/vercel/mcp-server"),
        install_command: Some("npx -y @vercel/mcp"),
        command: Some("npx"),
        args: &["-y", "@vercel/mcp"],
        env_vars: &["VERCEL_TOKEN"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-supabase",
        name: "Supabase",
        description: "Database, auth, storage, and edge functions via Supabase.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Database,
        tags: &["supabase", "postgres", "auth", "storage", "baas"],
        icon: "database",
        official: true,
        author: Some("Supabase"),
        license: Some("Apache-2.0"),
        source_url: Some("https://github.com/supabase-community/supabase-mcp"),
        install_command: Some("npx -y @supabase/mcp-server"),
        command: Some("npx"),
        args: &["-y", "@supabase/mcp-server"],
        env_vars: &["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-neon",
        name: "Neon",
        description: "Serverless Postgres. Branch databases, run queries, manage projects.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Database,
        tags: &["neon", "postgres", "serverless", "database"],
        icon: "database",
        official: true,
        author: Some("Neon"),
        license: Some("MIT"),
        source_url: Some("https://github.com/neondatabase/mcp-server-neon"),
        install_command: Some("npx -y @neondatabase/mcp-server-neon"),
        command: Some("npx"),
        args: &["-y", "@neondatabase/mcp-server-neon"],
        env_vars: &["NEON_API_KEY"],
        skill_template: None,
    },
    StaticEntry {
        id: "mcp-context7",
        name: "Context7",
        description: "Up-to-date library documentation. Query docs for any package.",
        kind: CatalogKind::McpServer,
        category: CatalogCategory::Development,
        tags: &["docs", "documentation", "libraries", "api-reference"],
        icon: "book-open",
        official: true,
        author: Some("Upstash"),
        license: Some("MIT"),
        source_url: Some("https://github.com/upstash/context7"),
        install_command: Some("npx -y @upstash/context7-mcp"),
        command: Some("npx"),
        args: &["-y", "@upstash/context7-mcp"],
        env_vars: &[],
        skill_template: None,
    },
];

// ─── API ──────────────────────────────────────────────────────────────────────

pub fn list_catalog() -> Vec<CatalogEntry> {
    EMBEDDED.iter().map(to_entry).collect()
}

pub fn list_catalog_by_kind(kind: CatalogKind) -> Vec<CatalogEntry> {
    EMBEDDED
        .iter()
        .filter(|e| e.kind == kind)
        .map(to_entry)
        .collect()
}

pub fn search_catalog(query: &str) -> Vec<CatalogEntry> {
    let q = query.to_lowercase();
    EMBEDDED
        .iter()
        .filter(|e| {
            e.name.to_lowercase().contains(&q)
                || e.description.to_lowercase().contains(&q)
                || e.tags.iter().any(|t| t.to_lowercase().contains(&q))
        })
        .map(to_entry)
        .collect()
}
